import {randomUUID} from 'node:crypto';
import {score,validateAnswers} from './instruments/scoring.mjs';
import {getInstrument,mini} from './instruments/registry.mjs';
import {assert,validateProfile,validateIntent,validateExport} from './contracts.mjs';
import {industries,roles,taxonomyVersion} from './taxonomy.mjs';
import {publicV1Profile,publicV1Attempt,emptyBackground,hasBackground,cleanV1Draft,FLOW_VERSION} from './profile/scope.mjs';
import {selectionVersion,validateChosenGoals,validateChosenConstraints,projectV1Choices,salaryOptions,cityOptions} from './profile/selections.mjs';
function validateV1Choices(d){
 validateChosenGoals(d.goals??[]);validateChosenConstraints(d.preferences??[]);
 if(d.cities!==undefined&&(!Array.isArray(d.cities)||d.cities.some(c=>!cityOptions.includes(c))))throw new ServiceError(422,'城市只接受预设选择');
 if(d.salary!==undefined&&d.salary!==null&&!salaryOptions.includes(d.salary))throw new ServiceError(422,'薪资只接受预设选择');
}
export class ServiceError extends Error{constructor(status,message){super(message);this.status=status;}}
export class Service{
 constructor(state={attempts:{},profiles:[],intents:[],metadata:{},scopeVersion:FLOW_VERSION,selectionVersion},save=()=>{}){this.state=state;this.save=save;}
 owned(owner,id){const a=this.state.attempts[id];if(!a)throw new ServiceError(404,'答题记录不存在');if(a.owner!==owner)throw new ServiceError(403,'没有访问权限');return a;}
 result(owner,id){const a=this.owned(owner,id);const tool=getInstrument(a.instrumentId);assert(a.version===tool.version,'当前服务未加载该历史题库，不能重算');assert(!a.draft.imported,'导入画像不包含原始答案，不能重算');return score(a.answers,a.instrumentId);}
 create(owner,mode='manual',instrumentId=mini.instrument){assert(['demo','manual'].includes(mode),'独立服务只支持demo/manual');const tool=getInstrument(instrumentId);const id=randomUUID();const a={id,owner,projectId:randomUUID(),profileId:randomUUID(),mode,instrumentId:tool.instrument,version:tool.version,revision:1,answers:{},draft:{},step:0};this.state.attempts[id]=a;this.save();return a;}
 update(owner,id,input){const a=this.owned(owner,id);if(input.expectedRevision!==a.revision)throw new ServiceError(409,'另一个页面已保存，请刷新后重试');const tool=getInstrument(a.instrumentId);assert(a.version===tool.version&&input.version===a.version,'题库版本不一致');validateAnswers(input.answers??{},a.instrumentId);assert(input.draft===undefined||input.draft&&typeof input.draft==='object'&&!Array.isArray(input.draft),'草稿错误');if(input.draft){assert(Object.keys(input.draft).every(k=>Object.hasOwn(cleanV1Draft(input.draft),k)),'草稿包含已停用字段或未知字段');validateV1Choices(input.draft);}assert(input.step===undefined||Number.isInteger(input.step)&&input.step>=0&&input.step<=7,'步骤错误');Object.assign(a.answers,input.answers??{});if(input.draft){const imported=a.draft.imported;a.draft=structuredClone(input.draft);if(imported)a.draft.imported=true;}if(input.step!==undefined)a.step=input.step;a.revision++;this.save();return a;}
 confirm(owner,id,input){const a=this.owned(owner,id);if(input.expectedRevision!==a.revision)throw new ServiceError(409,'记录已更新，请刷新');assert(input.confirmed===true,'请本人确认完整画像');assert(!hasBackground(input.background),'A已停用学历、技能和经历采集；仅允许空background用于兼容');assert(!input.correction,'当前版本不接收自由填写补充说明');validateChosenGoals(input.goals);validateChosenConstraints(input.preferences);assert(!a.selectionResetRequired||input.selectionResetConfirmed===true,'旧自由填写草稿已存档，请确认本次按当前选项重新选择');const result=this.result(owner,id);assert(a.instrumentId==='not-administered'||result.portrait.complete,'请完成完整英文题本，或新建暂不测评的画像');const revision=1+Math.max(0,...this.state.profiles.filter(p=>p.profileId===a.profileId).map(p=>p.revision));const p={schemaVersion:'1.0.0',profileId:a.profileId,revision,projectId:a.projectId,mode:a.mode,confirmedAt:new Date().toISOString(),assessment:{instrumentId:a.instrumentId,version:a.version,scores:result.scores,interpretation:result.interpretation,status:'confirmed',validation:'prototype'},background:emptyBackground(),goals:input.goals,preferences:input.preferences};validateProfile(p);this.state.profiles.push(structuredClone(p));this.state.metadata[`${p.profileId}:${revision}`]={coverage:result.coverage,portrait:structuredClone(result.portrait),selectionVersion,taxonomyVersion,assessmentRevision:a.revision,answersSnapshot:structuredClone(a.answers)};a.selectionResetRequired=false;a.revision++;this.save();return p;}
 intent(owner,input){const a=this.owned(owner,input.assessmentId);const p=this.state.profiles.find(p=>p.profileId===a.profileId&&p.revision===input.profileRevision);assert(p,'指定画像版本不存在');assert(Array.isArray(input.industryTags)&&input.industryTags.every(id=>industries.some(x=>x.id===id)),'未知行业ID');assert(Array.isArray(input.roleTypes)&&input.roleTypes.every(id=>roles.some(x=>x.id===id)),'未知岗位ID');const previous=this.state.intents.filter(i=>i.projectId===a.projectId);const i={schemaVersion:'1.0.0',intentId:previous[0]?.intentId??randomUUID(),revision:previous.length+1,projectId:a.projectId,profileId:p.profileId,profileRevision:p.revision,mode:p.mode,industryTags:[...new Set(input.industryTags)],industryCodes:[...new Set(industries.filter(x=>input.industryTags.includes(x.id)).flatMap(x=>x.codes))],roleTypes:[...new Set(input.roleTypes)],cities:p.preferences.find(x=>x.key==='city'&&x.confirmed)?.value??[],filters:p.preferences.map(x=>({key:x.key,value:x.confirmed?x.value:null,strength:x.confirmed?x.strength:'unknown'})),maxCandidates:input.maxCandidates??3};validateIntent(i,p);this.state.intents.push(structuredClone(i));this.save();return i;}
 export(owner,projectId){assert(Object.values(this.state.attempts).some(a=>a.projectId===projectId&&a.owner===owner),'没有项目访问权限');const i=this.state.intents.filter(i=>i.projectId===projectId).at(-1);assert(i,'请先确认意向');const p=this.state.profiles.find(p=>p.profileId===i.profileId&&p.revision===i.profileRevision);return structuredClone({UserProfile:publicV1Profile(p),SearchIntent:i});}
 import(owner,input){validateExport(input);assert(!hasBackground(input.UserProfile.background),'交接文件包含已停用的能力资料；请使用不含能力信息的新版导出');validateChosenGoals(input.UserProfile.goals,{withStage:true});validateChosenConstraints(input.UserProfile.preferences);const tool=getInstrument(input.UserProfile.assessment.instrumentId);assert(input.UserProfile.assessment.version===tool.version,'导入题库版本不支持');const a=this.create(owner,input.UserProfile.mode,tool.instrument);const p=structuredClone(input.UserProfile),i=structuredClone(input.SearchIntent);p.projectId=a.projectId;p.profileId=a.profileId;p.revision=1;i.projectId=a.projectId;i.profileId=p.profileId;i.profileRevision=1;i.intentId=randomUUID();i.revision=1;this.state.profiles.push(p);this.state.intents.push(i);a.draft=projectV1Choices({goals:p.goals,preferences:p.preferences,cities:i.cities,salary:p.preferences.find(x=>x.key==='min_fixed_monthly_salary')?.value??null,industryTags:i.industryTags,roleTypes:i.roleTypes,imported:true});a.step=7;this.save();return {attempt:a,UserProfile:p,SearchIntent:i};}
}

