import {randomUUID} from 'node:crypto';
import {score,version,instrumentId,validateAnswers} from './questionnaire.mjs';
import {assert,validateProfile,validateIntent,validateExport} from './contracts.mjs';
import {industries,roles,taxonomyVersion} from './taxonomy.mjs';
export class ServiceError extends Error{constructor(status,message){super(message);this.status=status;}}
export class Service{
 constructor(state={attempts:{},profiles:[],intents:[],metadata:{}},save=()=>{}){this.state=state;this.save=save;}
 owned(owner,id){const a=this.state.attempts[id];if(!a)throw new ServiceError(404,'答题记录不存在');if(a.owner!==owner)throw new ServiceError(403,'没有访问权限');return a;}
 result(owner,id){const a=this.owned(owner,id);assert(a.version===version,'当前服务未加载该历史题库，不能重算');return score(a.answers);}
 create(owner,mode='manual'){assert(['demo','manual'].includes(mode),'独立服务只支持demo/manual');const id=randomUUID();const a={id,owner,projectId:randomUUID(),profileId:randomUUID(),mode,version,revision:1,answers:{},draft:{},step:0};this.state.attempts[id]=a;this.save();return a;}
 update(owner,id,input){const a=this.owned(owner,id);if(input.expectedRevision!==a.revision)throw new ServiceError(409,'另一个页面已保存，请刷新后重试');validateAnswers(input.answers??{});assert(input.version===a.version,'题库版本不一致');assert(input.draft===undefined||input.draft&&typeof input.draft==='object'&&!Array.isArray(input.draft),'草稿错误');assert(input.step===undefined||Number.isInteger(input.step)&&input.step>=0&&input.step<=7,'步骤错误');Object.assign(a.answers,input.answers??{});if(input.draft)a.draft=structuredClone(input.draft);if(input.step!==undefined)a.step=input.step;a.revision++;this.save();return a;}
 confirm(owner,id,input){const a=this.owned(owner,id);if(input.expectedRevision!==a.revision)throw new ServiceError(409,'记录已更新，请刷新');assert(input.confirmed===true,'请本人确认完整画像');const result=this.result(owner,id);const revision=1+Math.max(0,...this.state.profiles.filter(p=>p.profileId===a.profileId).map(p=>p.revision));const p={schemaVersion:'1.0.0',profileId:a.profileId,revision,projectId:a.projectId,mode:a.mode,confirmedAt:new Date().toISOString(),assessment:{instrumentId,version:a.version,scores:result.scores,interpretation:result.interpretation,status:'confirmed',validation:'prototype'},background:input.background,goals:input.goals,preferences:input.preferences};validateProfile(p);this.state.profiles.push(structuredClone(p));this.state.metadata[`${p.profileId}:${revision}`]={coverage:result.coverage,portrait:structuredClone(result.portrait),correction:input.correction??'',taxonomyVersion,assessmentRevision:a.revision,answersSnapshot:structuredClone(a.answers)};a.revision++;this.save();return p;}
 intent(owner,input){const a=this.owned(owner,input.assessmentId);const p=this.state.profiles.find(p=>p.profileId===a.profileId&&p.revision===input.profileRevision);assert(p,'指定画像版本不存在');assert(Array.isArray(input.industryTags)&&input.industryTags.every(id=>industries.some(x=>x.id===id)),'未知行业ID');assert(Array.isArray(input.roleTypes)&&input.roleTypes.every(id=>roles.some(x=>x.id===id)),'未知岗位ID');const previous=this.state.intents.filter(i=>i.projectId===a.projectId);const i={schemaVersion:'1.0.0',intentId:previous[0]?.intentId??randomUUID(),revision:previous.length+1,projectId:a.projectId,profileId:p.profileId,profileRevision:p.revision,mode:p.mode,industryTags:[...new Set(input.industryTags)],industryCodes:[...new Set(industries.filter(x=>input.industryTags.includes(x.id)).flatMap(x=>x.codes))],roleTypes:[...new Set(input.roleTypes)],cities:p.preferences.find(x=>x.key==='city'&&x.confirmed)?.value??[],filters:p.preferences.map(x=>({key:x.key,value:x.confirmed?x.value:null,strength:x.confirmed?x.strength:'unknown'})),maxCandidates:input.maxCandidates??3};validateIntent(i,p);this.state.intents.push(structuredClone(i));this.save();return i;}
 export(owner,projectId){assert(Object.values(this.state.attempts).some(a=>a.projectId===projectId&&a.owner===owner),'没有项目访问权限');const i=this.state.intents.filter(i=>i.projectId===projectId).at(-1);assert(i,'请先确认意向');const p=this.state.profiles.find(p=>p.profileId===i.profileId&&p.revision===i.profileRevision);return structuredClone({UserProfile:p,SearchIntent:i});}
 import(owner,input){validateExport(input);const a=this.create(owner,input.UserProfile.mode);const p=structuredClone(input.UserProfile),i=structuredClone(input.SearchIntent);p.projectId=a.projectId;p.profileId=a.profileId;p.revision=1;i.projectId=a.projectId;i.profileId=p.profileId;i.profileRevision=1;i.intentId=randomUUID();i.revision=1;this.state.profiles.push(p);this.state.intents.push(i);a.draft={education:p.background.education??'',major:p.background.major??'',skills:p.background.skills.join('\n'),experiences:p.background.experiences.map(x=>x.text).join('\n'),goals:p.goals.join('\n'),preferences:p.preferences,cities:i.cities.join('，'),salary:p.preferences.find(x=>x.key==='min_fixed_monthly_salary')?.value??'',industryTags:i.industryTags,roleTypes:i.roleTypes,imported:true};a.step=7;this.save();return {attempt:a,UserProfile:p,SearchIntent:i};}
}

