import {mountSurvey} from './survey-adapter.mjs';
const app=document.querySelector('#app'),notice=document.querySelector('#notice');
const names=['开始','职业问卷','画像与目标','行业方向','岗位类型','现实条件','确认摘要','完成'];
let bank,attempt,result,exported,page=0,busy=false,survey;
const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines=x=>String(x??'').split(/[\n,，]/).map(x=>x.trim()).filter(Boolean);
async function api(path,method='GET',body){const r=await fetch('/api/a/'+path,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const x=await r.json();if(!r.ok)throw new Error(x.error.message);return x;}
const draft=()=>attempt?.draft??{};
function field(id,label,value='',type='text'){return `<label for="${id}">${label}</label><input id="${id}" type="${type}" value="${escape(value)}">`;}
function area(id,label,value=''){return `<label for="${id}">${label}</label><textarea id="${id}">${escape(value)}</textarea>`;}
function actions(back=true,next='继续'){return `<div class="actions">${back?'<button id="back">上一步</button>':'<span></span>'}<button id="next" class="primary">${next}</button></div>`;}
async function save(step=attempt.step){attempt=await api(`assessments/${attempt.id}/answers`,'PATCH',{version:attempt.version,expectedRevision:attempt.revision,answers:attempt.answers,draft:attempt.draft,step});}
function capture(){const d=draft();if(attempt.step===1&&survey){const x=survey.capture();attempt.answers=x.answers;d.questionPage=x.page;}
 if(attempt.step===2){for(const k of ['goals','correction'])d[k]=document.querySelector('#'+k).value;}
 if(attempt.step===3||attempt.step===4)d[attempt.step===3?'industryTags':'roleTypes']=[...document.querySelectorAll('input[name=selection]:checked')].map(x=>x.value);
 if(attempt.step===5){d.cities=document.querySelector('#cities').value;d.salary=document.querySelector('#salary').value;d.preferences=['city','min_fixed_monthly_salary','accept_sales_kpi','accept_travel','accept_outsourcing'].map(key=>{const strength=document.querySelector(`#${key}-strength`).value;const raw=key==='city'?lines(d.cities):key==='min_fixed_monthly_salary'?(d.salary===''?null:Number(d.salary)):document.querySelector('#'+key).value;const value=strength==='unknown'?null:typeof raw==='string'?(raw===''?null:raw==='true'):raw;return {key,value,strength:value===null||Array.isArray(value)&&value.length===0?'unknown':strength,confirmed:value!==null&&!(Array.isArray(value)&&value.length===0)&&document.querySelector(`#${key}-confirmed`).checked};});}
 attempt.draft=d;
}
function render(){survey?.dispose();survey=null;notice.textContent='';document.querySelector('#steps').innerHTML=names.map((n,i)=>`<div class="${i===(attempt?.step??0)?'active':''}">${String(i+1).padStart(2,'0')} ${n}</div>`).join('');const d=draft();const step=attempt?.step??0;
 if(step===0)app.innerHTML=`<p class="eyebrow">CAREER PROFILE</p><h2>先整理自己，再寻找机会。</h2><p class="muted">职业兴趣、求职需求和现实条件分别记录，最终由你确认。</p><div class="card"><h3>选择整理方式</h3><label>职业兴趣<select id="instrument"><option value="not-administered">暂不测评，兴趣保持未知</option><option value="onet-mini-ip">O*NET Mini-IP · 官方英文完整30题</option></select></label><p class="muted">目前没有已核实可用的中文题本。英文题目不翻译、不改写；只测自报兴趣。工作价值观量表仍待核实，本轮不提供分数。旧48题与记录已封存，不能恢复使用。</p><label>数据模式<select id="mode"><option value="manual">本人手动填写</option><option value="demo">演示模式（填写内容仍需明确标记为合成）</option></select></label><p class="muted">答案与草稿保存在本机服务，当前浏览器会话可恢复；不发送给外部模型。</p></div>${actions(false,'开始整理')}<div class="card"><label>重新导入当前格式的交接文件<input type="file" id="import" accept=".json,application/json"></label><p class="muted">导入创建新项目；旧48题文件被拒绝，不转成新测评。</p></div>`;
 if(step===1)app.innerHTML=`<p class="eyebrow">O*NET MINI-IP · ENGLISH · 2016</p><h2>你愿意从事哪些工作活动？</h2><p class="muted">按你对活动本身的兴趣回答，不按技能、教育要求或收入判断。原始英文完整30题。Unsure 是有效中间答案；缺答时不生成分数。</p><div id="survey"></div><div class="actions"><button id="back">返回开始</button><button id="save">保存草稿</button><button id="next" class="primary">保存并查看画像</button></div><p class="muted">O*NET® Career Exploration Tools · U.S. Department of Labor, Employment and Training Administration. <a href="https://www.onetcenter.org/dl_files/Mini-IP.pdf" target="_blank" rel="noopener">原始题本</a> · <a href="https://www.onetcenter.org/license_tools.html" target="_blank" rel="noopener">CC BY-ND 4.0 许可与署名</a>。软件集成未获原工具提供方认可或验证。</p>`;
 if(step===2)app.innerHTML=`<p class="eyebrow">YOUR PROFILE · DRAFT</p><h2>核对兴趣结果与求职目标。</h2><p class="muted">尚未由你确认。兴趣结果不会自动生成硬约束。</p><div class="card">${Object.entries(result.scores).map(([key,v])=>`<div class="score"><span>${bank.labels[key]}</span><div class="track"><progress max="100" value="${v??0}"></progress></div><small>${result.rawScores[key]===null?'未知':result.rawScores[key]+'/20'} · 展示 ${v??'未知'}</small></div>`).join('')}<p class="muted">${escape(result.interpretation)}</p><p class="muted">0–100 仅为原始分乘5的界面转换，不是百分位，没有高低阈值。${escape(result.portrait.basis)}</p>${area('correction','本人补充说明（不修改测评分数）',d.correction)}</div><div class="card"><h3>求职目标</h3>${area('goals','求职目标（可留空）',d.goals)}</div>${actions()}`;
 if(step===3||step===4){const industry=step===3,list=industry?bank.industries:bank.roles,chosen=d[industry?'industryTags':'roleTypes']??[];app.innerHTML=`<p class="eyebrow">${industry?'INDUSTRY':'ROLE'} DIRECTION</p><h2>${industry?'哪些领域让你想进一步了解？':'你想做哪类工作？'}</h2><p class="muted">可多选，也可暂不选择。行业和岗位不是一一对应。</p><input id="search" placeholder="搜索${industry?'行业':'岗位'}"><div class="grid card" id="choices">${list.map(x=>`<label class="tile" data-name="${escape(x.name)}"><input type="checkbox" name="selection" value="${x.id}" ${chosen.includes(x.id)?'checked':''}> <strong>${x.name}</strong><small>${x.description}</small><small>${industry?'门类候选：'+x.codes.join(' / ')+' · 按具体业务核实':'产品工作类型 · 官方代码待核验'}</small></label>`).join('')}</div>${actions()}`;}
 if(step===5){const prefs=d.preferences??[];const control=(key,label,extra)=>{const p=prefs.find(p=>p.key===key);return `<div class="card"><h3>${label}</h3>${extra}<label>要求程度<select id="${key}-strength">${[['unknown','不确定'],['soft','软偏好'],['hard','硬要求']].map(([v,t])=>`<option value="${v}" ${p?.strength===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="check"><input type="checkbox" id="${key}-confirmed" ${p?.confirmed?'checked':''}> 我明确确认这项条件</label></div>`;};app.innerHTML=`<p class="eyebrow">PREFERENCES & BOUNDARIES</p><h2>哪些条件，对你很重要？</h2><p class="muted">未回答或未确认保持未知；问卷不能替你决定硬要求。</p>${control('city','工作城市',field('cities','城市（逗号或换行分隔）',d.cities))}${control('min_fixed_monthly_salary','最低固定月薪',field('salary','人民币 / 月，税前固定部分；可留空',d.salary,'number'))}${[['accept_sales_kpi','是否接受销售指标'],['accept_travel','是否接受出差'],['accept_outsourcing','是否接受外包用工']].map(([key,label])=>{const p=prefs.find(x=>x.key===key);return control(key,label,`<select id="${key}"><option value="">不确定</option><option value="true" ${p?.value===true?'selected':''}>接受</option><option value="false" ${p?.value===false?'selected':''}>不接受</option></select>`);}).join('')}${actions(true,'查看确认摘要')}`;}
 if(step===6)app.innerHTML=`<p class="eyebrow">REVIEW & CONFIRM</p><h2>这是由你确认的方向。</h2><div class="card"><dl class="summary"><dt>数据模式</dt><dd>${attempt.mode==='demo'?'合成演示':'本人手动填写'}</dd><dt>画像补充</dt><dd>${escape(d.correction||'无')}</dd><dt>目标</dt><dd>${escape(d.goals||'尚不确定')}</dd><dt>行业 / 岗位</dt><dd>${escape((d.industryTags??[]).map(id=>bank.industries.find(x=>x.id===id)?.name).join('、')||'尚不确定')} / ${escape((d.roleTypes??[]).map(id=>bank.roles.find(x=>x.id===id)?.name).join('、')||'尚不确定')}</dd><dt>现实条件</dt><dd>${(d.preferences??[]).map(p=>`${escape(p.key)}：${escape(p.confirmed?JSON.stringify(p.value):'未知（未确认）')} · ${p.confirmed?p.strength:'unknown'}`).join('<br>')}</dd></dl><label class="check"><input id="confirm" type="checkbox"> 我已核对画像与意向，同意保存此次确认版本。</label></div>${actions(true,'确认并生成意向')}`;
 if(step===7)app.innerHTML=`<p class="eyebrow">READY FOR YOUR NEXT STEP</p><h2>你的求职画像已保存。</h2><p class="muted">画像版本 ${exported.UserProfile.revision} · 意向版本 ${exported.SearchIntent.revision} · ${exported.UserProfile.mode}</p><div class="card"><h3>交给下一步的两份资料</h3><p>UserProfile 用于 C 的个性化分析；SearchIntent 用于 B 的检索。当前仅完成 A。</p><button class="primary" id="download">下载 JSON</button><details><summary>查看交接内容</summary><pre>${escape(JSON.stringify(exported,null,2))}</pre></details></div><div class="actions"><button id="edit">修改并创建新版本</button><button id="new">新建画像</button></div>`;
 bind();if(step===1){const currentId=attempt.id;survey=mountSurvey(document.getElementById('survey'),bank,attempt,()=>run(async()=>{if(attempt?.id!==currentId||attempt.step!==1)return;capture();await save();notice.textContent='已自动保存';}),()=>document.getElementById('next').click());}}
let navigationPending=false;
function on(id,fn){const el=document.getElementById(id);if(el)el.onclick=()=>{if(navigationPending)return;navigationPending=true;app.querySelectorAll('.actions button').forEach(x=>x.disabled=true);run(fn).finally(()=>{navigationPending=false;app.querySelectorAll('.actions button').forEach(x=>x.disabled=false);});};}
let queue=Promise.resolve();
// Serialize saves and navigation without disabling a clicked button during input blur.
function run(fn){queue=queue.then(async()=>{busy=true;try{await fn();}catch(e){notice.textContent=e.message+'。草稿保留在当前页面。';if(e.message.includes('刷新'))notice.textContent+=' 请刷新恢复最新服务端版本。';}finally{busy=false;}});return queue;}
function bind(){on('next',async()=>{clearTimeout(draftTimer);const step=attempt?.step??0;if(step===0){if(!attempt){attempt=await api('assessments','POST',{mode:document.querySelector('#mode').value,instrumentId:document.querySelector('#instrument').value});attempt.draft={};}await save(attempt.instrumentId==='not-administered'?2:1);if(attempt.step===2)result=await api(`assessments/${attempt.id}/score`,'POST',{});}
 else if(step===1){capture();await save(1);result=await api(`assessments/${attempt.id}/score`,'POST',{});if(!result.portrait.complete)throw new Error('请完成30题；可保存后稍后恢复。若暂不测评，请新建画像选择暂不测评');await save(2);}
 else if(step===6){if(!document.querySelector('#confirm').checked)throw new Error('请勾选本人确认');const d=draft();const p=await api(`profiles/${attempt.profileId}/confirm`,'PUT',{assessmentId:attempt.id,expectedRevision:attempt.revision,confirmed:true,goals:lines(d.goals),preferences:d.preferences??[],correction:d.correction??''});attempt=await api('assessments/'+attempt.id);const i=await api('intents','POST',{assessmentId:attempt.id,profileRevision:p.revision,industryTags:d.industryTags??[],roleTypes:d.roleTypes??[],maxCandidates:3});exported={UserProfile:p,SearchIntent:i};await save(7);}
 else{capture();await save(step+1);}render();});
 on('back',async()=>{clearTimeout(draftTimer);capture();await save(attempt.step===2&&attempt.instrumentId==='not-administered'?0:attempt.step-1);render();});on('save',async()=>{capture();await save();notice.textContent='草稿已保存。';});on('download',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(exported,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='xray-a-profile.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});on('edit',async()=>{if(draft().imported)throw new Error('导入文件不含原始问卷答案，请新建画像后重新填写');await save(2);result=await api(`assessments/${attempt.id}/score`,'POST',{});render();});on('new',()=>{attempt=null;render();});const search=document.querySelector('#search');if(search)search.oninput=()=>document.querySelectorAll('.tile').forEach(t=>t.hidden=!t.textContent.toLowerCase().includes(search.value.toLowerCase()));const file=document.querySelector('#import');if(file)file.onchange=()=>run(async()=>{const text=await file.files[0].text();if(text.length>256000)throw new Error('文件过大');const x=await api('import','POST',JSON.parse(text));attempt=x.attempt;exported={UserProfile:x.UserProfile,SearchIntent:x.SearchIntent};render();});}
let draftTimer;app.addEventListener('input',e=>{if(attempt&&attempt.step>=2&&attempt.step<=5&&e.target.id!=='search'){clearTimeout(draftTimer);draftTimer=setTimeout(()=>{if(!busy)run(async()=>{capture();await save();notice.textContent='已自动保存';});},350);}});
app.addEventListener('change',e=>{if(attempt&&attempt.step>=2&&attempt.step<=5&&e.target.id!=='search')run(async()=>{capture();await save();notice.textContent='已自动保存';});});
await run(async()=>{bank=await api('bootstrap');attempt=bank.attempts.at(-1);if(attempt){if(!attempt.draft.imported)result=await api(`assessments/${attempt.id}/score`,'POST',{});if(attempt.step===7)exported=await api(`export/${attempt.projectId}`);}render();});



