const app=document.querySelector('#app'),notice=document.querySelector('#notice');
const names=['开始','职业问卷','画像与经历','行业方向','岗位类型','现实条件','确认摘要','完成'];
let bank,attempt,result,exported,page=0,busy=false;
const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines=x=>String(x??'').split(/[\n,，]/).map(x=>x.trim()).filter(Boolean);
async function api(path,method='GET',body){const r=await fetch('/api/a/'+path,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const x=await r.json();if(!r.ok)throw new Error(x.error.message);return x;}
const draft=()=>attempt?.draft??{};
function field(id,label,value='',type='text'){return `<label for="${id}">${label}</label><input id="${id}" type="${type}" value="${escape(value)}">`;}
function area(id,label,value=''){return `<label for="${id}">${label}</label><textarea id="${id}">${escape(value)}</textarea>`;}
function actions(back=true,next='继续'){return `<div class="actions">${back?'<button id="back">上一步</button>':'<span></span>'}<button id="next" class="primary">${next}</button></div>`;}
async function save(step=attempt.step){attempt=await api(`assessments/${attempt.id}/answers`,'PATCH',{version:attempt.version,expectedRevision:attempt.revision,answers:attempt.answers,draft:attempt.draft,step});}
function capture(){const d=draft();if(attempt.step===1){document.querySelectorAll('.question input:checked').forEach(x=>{attempt.answers[x.name]=x.value==='unknown'?null:Number(x.value);});d.questionPage=page;}
 if(attempt.step===2){for(const k of ['education','major','skills','experiences','goals','correction'])d[k]=document.querySelector('#'+k).value;}
 if(attempt.step===3||attempt.step===4)d[attempt.step===3?'industryTags':'roleTypes']=[...document.querySelectorAll('input[name=selection]:checked')].map(x=>x.value);
 if(attempt.step===5){d.cities=document.querySelector('#cities').value;d.salary=document.querySelector('#salary').value;d.preferences=['city','min_fixed_monthly_salary','accept_sales_kpi','accept_travel','accept_outsourcing'].map(key=>{const strength=document.querySelector(`#${key}-strength`).value;const raw=key==='city'?lines(d.cities):key==='min_fixed_monthly_salary'?(d.salary===''?null:Number(d.salary)):document.querySelector('#'+key).value;const value=strength==='unknown'?null:typeof raw==='string'?(raw===''?null:raw==='true'):raw;return {key,value,strength:value===null||Array.isArray(value)&&value.length===0?'unknown':strength,confirmed:value!==null&&!(Array.isArray(value)&&value.length===0)&&document.querySelector(`#${key}-confirmed`).checked};});}
 attempt.draft=d;
}
function render(){notice.textContent='';document.querySelector('#steps').innerHTML=names.map((n,i)=>`<div class="${i===(attempt?.step??0)?'active':''}">${String(i+1).padStart(2,'0')} ${n}</div>`).join('');const d=draft();const step=attempt?.step??0;
 if(step===0)app.innerHTML=`<p class="eyebrow">CAREER PROFILE</p><h2>先整理自己，再寻找机会。</h2><p class="muted">一份可修改、可追溯的职业画像，帮助后续检索与分析。</p><div class="card"><h3>你会得到什么</h3><p>职业偏好 · 经历清单 · 行业与岗位意向 · 已确认的现实条件</p><p class="muted">48题自编原型，可选择不确定。问卷不证明实际能力。答案与草稿保存在本机服务的数据文件中，当前浏览器会话可恢复。不向外部模型发送材料。</p><label>数据模式<select id="mode"><option value="manual">本人手动填写</option><option value="demo">合成演示（明确标记）</option></select></label></div>${actions(false,'开始整理')}<div class="card"><label>已有导出文件？重新导入<input type="file" id="import" accept=".json,application/json"></label><p class="muted">导入后创建当前会话的新项目，保留来源模式；不覆盖其他项目。</p></div>`;
 if(step===1){const qs=bank.questions.slice(page*8,page*8+8);const answered=Object.keys(attempt.answers).length;app.innerHTML=`<p class="eyebrow">QUESTIONNAIRE · ${page+1}/6</p><h2>按你现在的感受回答。</h2><p class="muted">已作答 ${answered}/48 · 没有正确答案，不确定不计入有效分数。</p><div class="card">${qs.map((q,index)=>`<div class="question"><p><span class="muted">${page*8+index+1}. ${q.group}</span><br>${q.text}</p><div class="options">${q.options.map(o=>`<label><input type="radio" name="${q.id}" value="${o.id}" ${Object.hasOwn(attempt.answers,q.id)&&attempt.answers[q.id]===o.value?'checked':''}> ${o.text}</label>`).join('')}</div></div>`).join('')}</div><div class="actions"><button id="prevQuestions">${page===0?'返回开始':'上一组'}</button><button id="save">保存草稿</button><button id="next" class="primary">${page===5?'查看画像':'下一组'}</button></div>`;}
 if(step===2)app.innerHTML=`<p class="eyebrow">YOUR PROFILE · DRAFT</p><h2>这些倾向，符合你吗？</h2><p class="muted">分数描述偏好，低分不表示能力不足。尚未确认。</p><div class="card">${Object.entries(result.scores).map(([key,v])=>`<div class="score"><span>${bank.labels[key]}</span><div class="track"><progress max="100" value="${v??0}"></progress></div><small>${v??'未知'} · ${result.coverage[key].answered}/${result.coverage[key].total}</small></div>`).join('')}<p class="muted">${escape(result.interpretation)}</p>${area('correction','画像纠正 / 补充说明（保留计算结果）',d.correction)}</div><div class="card"><h3>用经历补充你的画像</h3><p class="muted">只填写希望用于分析的信息，无需联系方式。当前模型提取未接入，请手填。</p><div class="grid">${field('education','学历（可留空）',d.education)}${field('major','专业（可留空）',d.major)}</div>${area('skills','技能（每行一项）',d.skills)}${area('experiences','项目 / 实习经历（每行一项，本人填写）',d.experiences)}${area('goals','求职目标（每行一项）',d.goals)}</div>${actions()}`;
 if(step===3||step===4){const industry=step===3,list=industry?bank.industries:bank.roles,chosen=d[industry?'industryTags':'roleTypes']??[];app.innerHTML=`<p class="eyebrow">${industry?'INDUSTRY':'ROLE'} DIRECTION</p><h2>${industry?'哪些领域让你想进一步了解？':'你想做哪类工作？'}</h2><p class="muted">可多选，也可暂不选择。行业和岗位不是一一对应。</p><input id="search" placeholder="搜索${industry?'行业':'岗位'}"><div class="grid card" id="choices">${list.map(x=>`<label class="tile" data-name="${escape(x.name)}"><input type="checkbox" name="selection" value="${x.id}" ${chosen.includes(x.id)?'checked':''}> <strong>${x.name}</strong><small>${x.description}</small><small>${industry?'门类候选：'+x.codes.join(' / ')+' · 按具体业务核实':'产品工作类型 · 官方代码待核验'}</small></label>`).join('')}</div>${actions()}`;}
 if(step===5){const prefs=d.preferences??[];const control=(key,label,extra)=>{const p=prefs.find(p=>p.key===key);return `<div class="card"><h3>${label}</h3>${extra}<label>要求程度<select id="${key}-strength">${[['unknown','不确定'],['soft','软偏好'],['hard','硬要求']].map(([v,t])=>`<option value="${v}" ${p?.strength===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="check"><input type="checkbox" id="${key}-confirmed" ${p?.confirmed?'checked':''}> 我明确确认这项条件</label></div>`;};app.innerHTML=`<p class="eyebrow">PREFERENCES & BOUNDARIES</p><h2>哪些条件，对你很重要？</h2><p class="muted">未回答或未确认保持未知；问卷不能替你决定硬要求。</p>${control('city','工作城市',field('cities','城市（逗号或换行分隔）',d.cities))}${control('min_fixed_monthly_salary','最低固定月薪',field('salary','人民币 / 月，税前固定部分；可留空',d.salary,'number'))}${[['accept_sales_kpi','是否接受销售指标'],['accept_travel','是否接受出差'],['accept_outsourcing','是否接受外包用工']].map(([key,label])=>{const p=prefs.find(x=>x.key===key);return control(key,label,`<select id="${key}"><option value="">不确定</option><option value="true" ${p?.value===true?'selected':''}>接受</option><option value="false" ${p?.value===false?'selected':''}>不接受</option></select>`);}).join('')}${actions(true,'查看确认摘要')}`;}
 if(step===6)app.innerHTML=`<p class="eyebrow">REVIEW & CONFIRM</p><h2>这是由你确认的方向。</h2><div class="card"><dl class="summary"><dt>数据模式</dt><dd>${attempt.mode==='demo'?'合成演示':'本人手动填写'}</dd><dt>学历 / 专业</dt><dd>${escape(d.education||'未知')} / ${escape(d.major||'未知')}</dd><dt>技能与经历</dt><dd>${escape(d.skills||'未填写')}<br>${escape(d.experiences||'未填写')}</dd><dt>画像补充</dt><dd>${escape(d.correction||'无')}</dd><dt>目标</dt><dd>${escape(d.goals||'尚不确定')}</dd><dt>行业 / 岗位</dt><dd>${escape((d.industryTags??[]).map(id=>bank.industries.find(x=>x.id===id)?.name).join('、')||'尚不确定')} / ${escape((d.roleTypes??[]).map(id=>bank.roles.find(x=>x.id===id)?.name).join('、')||'尚不确定')}</dd><dt>现实条件</dt><dd>${(d.preferences??[]).map(p=>`${escape(p.key)}：${escape(p.confirmed?JSON.stringify(p.value):'未知（未确认）')} · ${p.confirmed?p.strength:'unknown'}`).join('<br>')}</dd></dl><label class="check"><input id="confirm" type="checkbox"> 我已核对画像、经历与意向，同意保存此次确认版本。</label></div>${actions(true,'确认并生成意向')}`;
 if(step===7)app.innerHTML=`<p class="eyebrow">READY FOR YOUR NEXT STEP</p><h2>你的求职画像已保存。</h2><p class="muted">画像版本 ${exported.UserProfile.revision} · 意向版本 ${exported.SearchIntent.revision} · ${exported.UserProfile.mode}</p><div class="card"><h3>交给下一步的两份资料</h3><p>UserProfile 用于 C 的个性化分析；SearchIntent 用于 B 的检索。当前仅完成 A。</p><button class="primary" id="download">下载 JSON</button><details><summary>查看交接内容</summary><pre>${escape(JSON.stringify(exported,null,2))}</pre></details></div><div class="actions"><button id="edit">修改并创建新版本</button><button id="new">新建画像</button></div>`;
 bind();}
function on(id,fn){const el=document.getElementById(id);if(el)el.onclick=()=>run(fn);}
let queue=Promise.resolve();
function run(fn){queue=queue.then(async()=>{busy=true;try{await fn();}catch(e){notice.textContent=e.message+'。草稿保留在当前页面。';if(e.message.includes('刷新'))notice.textContent+=' 请刷新恢复最新服务端版本。';}finally{busy=false;}});return queue;}
function bind(){on('next',async()=>{const step=attempt?.step??0;if(step===0){attempt=await api('assessments','POST',{mode:document.querySelector('#mode').value});attempt.draft={};await save(1);page=0;}
 else if(step===1){capture();if(page<5){page++;attempt.draft.questionPage=page;await save(1);}else{await save(2);result=await api(`assessments/${attempt.id}/score`,'POST',{});}}
 else if(step===6){if(!document.querySelector('#confirm').checked)throw new Error('请勾选本人确认');const d=draft();const p=await api(`profiles/${attempt.profileId}/confirm`,'PUT',{assessmentId:attempt.id,expectedRevision:attempt.revision,confirmed:true,background:{education:d.education?.trim()||null,major:d.major?.trim()||null,skills:lines(d.skills),experiences:lines(d.experiences).map(text=>({text,source:'user',confirmed:true}))},goals:lines(d.goals),preferences:d.preferences??[],correction:d.correction??''});const i=await api('intents','POST',{assessmentId:attempt.id,profileRevision:p.revision,industryTags:d.industryTags??[],roleTypes:d.roleTypes??[],maxCandidates:3});exported={UserProfile:p,SearchIntent:i};await save(7);}
 else{capture();await save(step+1);}render();});
 on('back',async()=>{capture();await save(attempt.step-1);if(attempt.step===1)page=draft().questionPage??0;render();});on('prevQuestions',async()=>{capture();page=Math.max(0,page-1);attempt.draft.questionPage=page;await save(page===0&&document.querySelector('#prevQuestions').textContent==='返回开始'?0:1);render();});on('save',async()=>{capture();await save();notice.textContent='草稿已保存。';});on('download',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(exported,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='xray-a-profile.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});on('edit',async()=>{if(draft().imported)throw new Error('导入文件不含原始问卷答案，请新建画像后重新填写');await save(2);result=await api(`assessments/${attempt.id}/score`,'POST',{});render();});on('new',()=>{attempt=null;render();});const search=document.querySelector('#search');if(search)search.oninput=()=>document.querySelectorAll('.tile').forEach(t=>t.hidden=!t.textContent.toLowerCase().includes(search.value.toLowerCase()));const file=document.querySelector('#import');if(file)file.onchange=()=>run(async()=>{const text=await file.files[0].text();if(text.length>256000)throw new Error('文件过大');const x=await api('import','POST',JSON.parse(text));attempt=x.attempt;exported={UserProfile:x.UserProfile,SearchIntent:x.SearchIntent};render();});}
app.addEventListener('change',e=>{if(attempt&&attempt.step>=1&&attempt.step<=5&&e.target.id!=='search')run(async()=>{capture();await save();notice.textContent='已自动保存';});});
await run(async()=>{bank=await api('bootstrap');attempt=bank.attempts.at(-1);if(attempt){page=attempt.draft.questionPage??0;result=await api(`assessments/${attempt.id}/score`,'POST',{});if(attempt.step===7)exported=await api(`export/${attempt.projectId}`);}render();});

