const app=document.querySelector('#app'),notice=document.querySelector('#notice'),steps=document.querySelector('#steps');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let boot,session=null,data,step=0,queue=Promise.resolve(),out;
async function api(path,method='GET',body){const r=await fetch('/api/a/needs/'+path,{method,headers:{'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const x=await r.json();if(!r.ok)throw new Error(x.error?.message??'请求失败');return x;}
function error(e){notice.textContent=e instanceof SyntaxError?'文件不是有效的JSON，请检查文件内容。':e.message;}
function button(id,text,primary=false){return '<button id="'+id+'"'+(primary?' class="primary"':'')+'>'+text+'</button>';}
function action(id,fn){document.getElementById(id)?.addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;try{notice.textContent='';await fn();}catch(x){error(x);}finally{if(b.isConnected)b.disabled=false;}});}
function select(id,items,value,unknown='暂不确定'){return '<select id="'+id+'"><option value="">'+unknown+'</option>'+items.map(x=>'<option value="'+esc(x.id)+'"'+(String(value)===String(x.id)?' selected':'')+'>'+esc(x.text)+'</option>').join('')+'</select>';}
function save(){const snapshot=structuredClone(data),position=step;notice.textContent='正在保存…';queue=queue.catch(()=>{}).then(async()=>{session=await api('sessions/'+session.id,'PATCH',{expectedRevision:session.revision,questionnaireVersion:boot.catalog.version,data:snapshot,step:position});notice.textContent='已自动保存';});return queue;}
const checkOptions=(name,items,selected=[])=>'<div class="options">'+items.map(x=>'<label><input type="checkbox" name="'+name+'" value="'+esc(x.id)+'"'+(selected?.includes(x.id)?' checked':'')+'> '+esc(x.text)+'</label>').join('')+'</div>';
function nav(){steps.innerHTML=[...boot.catalog.topics.map(t=>t.title),'现实条件与方向','确认画像','已保存的需求'].map((text,i)=>'<div'+(session&&i===step?' class="active"':'')+'>'+esc(text)+'</div>').join('');}
function home(){nav();app.innerHTML='<div class="card"><h2>先了解你的求职需求</h2><p>选出你的求职需求和岗位意向，再查看哪些公司或岗位适合继续了解。</p><p class="muted">七个主题，通过选择填写；题目中还没想清楚的内容可以之后再补充。</p><div class="actions">'+button('start','开始新的判断',true)+button('continue','继续上次的判断')+'</div><p class="muted"><a href="/showcase">查看展示案例 →</a></p></div>';
 action('start',async()=>{session=await api('sessions','POST',{mode:'manual'});data=structuredClone(session.data);step=0;locateSession();await render();});
 action('continue',async()=>{location.href='/history';});
}
function topicPage(){const t=boot.catalog.topics[step];app.innerHTML='<div class="card"><p class="muted">主题 '+(step+1)+' / 7</p><h2>'+esc(t.title)+'</h2><p>'+esc(t.description)+'</p>'+t.questions.map(q=>'<fieldset class="question"><legend>'+esc(q.text)+'</legend>'+(q.kind==='single'?'<div class="options">'+q.options.map(o=>'<label><input type="radio" name="'+q.id+'" value="'+o.id+'"'+(data.answers[q.id]===o.id?' checked':'')+'> '+esc(o.text)+'</label>').join('')+'</div>':checkOptions(q.id,q.options,data.answers[q.id]))+'</fieldset>').join('')+'<div class="actions">'+(step?button('back','上一页'):button('home','返回开始'))+button('next',step===6?'下一步：现实条件':'下一主题',true)+'</div></div>';
 for(const input of app.querySelectorAll('input'))input.addEventListener('change',async e=>{try{const q=e.target.name;if(e.target.type==='radio')data.answers[q]=e.target.value;else{const list=[...app.querySelectorAll('input')].filter(el=>el.name===q);if(e.target.value==='unsure'&&e.target.checked)list.filter(el=>el.value!=='unsure').forEach(el=>el.checked=false);else if(e.target.checked)list.find(el=>el.value==='unsure').checked=false;data.answers[q]=list.filter(el=>el.checked).map(el=>el.value);if(!data.answers[q].length)data.answers[q]=null;}await save();}catch(x){error(x);}});
 action('home',async()=>{await save();session=null;const u=new URL(location.href);u.searchParams.delete('sessionId');u.searchParams.set('new','1');history.replaceState(null,'',u);home();});action('back',async()=>{step--;await save();await render();});action('next',async()=>{step++;await save();await render();});
}
function conditionsPage(){
 const labels=boot.conditions.labels,city=data.conditions.find(c=>c.key==='city');
 const tasks=data.goalIds.filter(id=>boot.opportunities.some(x=>x.id===id)),selectedTask=tasks.length===1?tasks[0]:null;
 const strengthSelect=c=>select(c.key+'-strength',[{id:'soft',text:'偏好，可结合其他条件考虑'},{id:'hard',text:'必须满足，由我明确确认'}],c.strength==='unknown'?null:c.strength,'未选择条件时保持未知');
 app.innerHTML='<div class="card"><h2>现实条件与行业、岗位方向</h2><p class="muted">可以保存尚未确定的需求；确认输出前，请选定工作机会、目标行业和岗位。“必须满足”仅在下一步由你确认后生效。</p><fieldset class="question"><legend>你这次主要想寻找哪种工作机会？（单选）</legend><div class="options">'+boot.opportunities.map(g=>'<label><input type="radio" name="opportunity" value="'+g.id+'"'+(selectedTask===g.id?' checked':'')+'> '+esc(g.text)+'</label>').join('')+'</div><p class="muted">如果同时考虑多种机会，先选择本次最优先的一种。</p></fieldset>'+(data.stageId!==null||data.goalIds.some(id=>!boot.opportunities.some(x=>x.id===id)&&!boot.expectationIds.includes(id))?'<p class="muted">旧求职阶段与任务保留在历史版本；请在这一页检查并确认本次工作机会。</p>':'')+'<h3>你希望进入哪些行业？（可多选）</h3>'+checkOptions('industries',boot.industries.map(x=>({id:x.id,text:x.name})),data.industryTags)+'<p class="muted">确认输出前至少选择一个行业；行业标签可能交叉。</p><h3>你希望从事哪些类型的岗位？（可多选）</h3>'+checkOptions('roles',boot.roles.map(x=>({id:x.id,text:x.name})),data.roleTypes)+'<p class="muted">确认输出前至少选择一种岗位；岗位标签不代表能力判断。</p><h3>希望工作带来的改善（可多选）</h3>'+checkOptions('expectations',boot.goals,data.goalIds)+'<div class="question"><h3>工作城市（可多选并排序）</h3><details id="city-choices"><summary>选择城市（可多选）</summary>'+checkOptions('cities',boot.conditions.cities.map(text=>({id:text,text})),city.value??[])+'</details><p class="muted">排序代表你的优先顺序，第一项最优先；用上移、下移调整。未选择表示暂不确定。</p><div id="city-order"></div>'+strengthSelect(city)+'</div>'+data.conditions.filter(c=>c.key!=='city').map(c=>'<div class="question"><label for="'+c.key+'">'+esc(labels[c.key])+'</label>'+select(c.key,c.key==='min_fixed_monthly_salary'?boot.conditions.salaries.map(n=>({id:String(n),text:'至少 '+n+' 元／月（人民币税前固定部分）'})):[{id:'true',text:'接受'},{id:'false',text:'不接受'}],c.value===null?null:String(c.value))+strengthSelect(c)+'</div>').join('')+'<div class="actions">'+button('back','上一页')+button('next','查看并确认侧写',true)+'</div></div>';
 function renderCities(){const xs=data.conditions.find(c=>c.key==='city').value??[];document.getElementById('city-order').innerHTML=xs.length?'<ol>'+xs.map((name,i)=>'<li>'+esc(name)+' <button type="button" data-city-index="'+i+'" data-city-action="up" aria-label="提高'+esc(name)+'优先级"'+(!i?' disabled':'')+'>上移</button> <button type="button" data-city-index="'+i+'" data-city-action="down" aria-label="降低'+esc(name)+'优先级"'+(i===xs.length-1?' disabled':'')+'>下移</button></li>').join('')+'</ol>':'<p class="muted">城市暂不确定</p>';}
 renderCities();
 const selected=name=>[...app.querySelectorAll('input[type=checkbox]')].filter(x=>x.name===name&&x.checked).map(x=>x.value);
 function collect(){
  const task=app.querySelector('input[name=opportunity]:checked')?.value;
  data.stageId=null;data.goalIds=[...(task?[task]:[]),...selected('expectations')];data.industryTags=selected('industries');data.roleTypes=selected('roles');
  data.conditions=data.conditions.map(c=>{let value;if(c.key==='city'){const chosen=selected('cities'),before=c.value??[];const order=[...before.filter(name=>chosen.includes(name)),...chosen.filter(name=>!before.includes(name))];value=order.length?order:null;}else{const raw=document.getElementById(c.key).value;value=raw===''?null:c.key==='min_fixed_monthly_salary'?Number(raw):raw==='true';}let strength=document.getElementById(c.key+'-strength').value;if(value===null)strength='unknown';else if(!strength)strength='soft';document.getElementById(c.key+'-strength').value=strength==='unknown'?'':strength;return {key:c.key,value,strength};});
 }
 app.onchange=async e=>{try{collect();if(e.target.name==='cities')renderCities();await save();}catch(x){error(x);}};
 document.getElementById('city-order').onclick=async e=>{const b=e.target.closest('button[data-city-action]');if(!b||b.disabled)return;try{collect();const xs=data.conditions.find(c=>c.key==='city').value,index=Number(b.dataset.cityIndex),target=index+(b.dataset.cityAction==='up'?-1:1);if(target<0||target>=xs.length)return;[xs[index],xs[target]]=[xs[target],xs[index]];renderCities();await save();}catch(x){error(x);}};
 action('back',async()=>{collect();step=6;await save();await render();});action('next',async()=>{
  collect();
  if(!app.querySelector('input[name=opportunity]:checked'))throw new Error('请选择本次主要寻找的工作机会；未确定时可保存，暂不能确认输出');
  if(!data.industryTags.length)throw new Error('请至少选择一个目标行业；未确定时可保存，暂不能确认输出');
  if(!data.roleTypes.length)throw new Error('请至少选择一种岗位类型；未确定时可保存，暂不能确认输出');
  step=8;await save();await render();
 });
}

function conditionDescription(c){const text=c.value===null?'暂不确定':c.key==='city'?c.value.join('、'):c.key==='min_fixed_monthly_salary'?'至少 '+c.value+' 元／月（人民币税前固定部分）':c.value?'接受':'不接受';return esc(boot.conditions.labels[c.key])+'：'+esc(text)+(c.strength==='hard'?'（必须满足）':c.strength==='soft'?'（偏好）':'');}
function descriptionHtml(description){return description.map(t=>'<div class="card"><h3>'+esc(t.title)+'</h3><p>'+esc(t.priority)+'</p><ul>'+t.details.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul><p>'+esc(t.policy)+'</p></div>').join('');}
async function review(){const p=await api('sessions/'+session.id+'/preview');app.innerHTML='<h2>确认你的求职需求侧写</h2><p class="muted">以下是根据你的选择整理的需求。重点不代表硬约束，信息不清楚不代表企业有风险；未选信息保持未知。</p>'+descriptionHtml(p.description)+'<div class="card"><h3>现实条件</h3><ul>'+data.conditions.map(c=>'<li>'+conditionDescription(c)+'</li>').join('')+'</ul><h3>目标行业与岗位</h3><p>行业：'+esc(data.industryTags.map(id=>boot.industries.find(x=>x.id===id).name).join('、')||'暂不确定')+'</p><p>岗位：'+esc(data.roleTypes.map(id=>boot.roles.find(x=>x.id===id).name).join('、')||'暂不确定')+'</p><label class="check"><input type="checkbox" id="confirmed"> 我已检查以上选择；有值的现实条件及其“偏好／必须满足”设置由我确认，未知项保持未知。</label><div class="actions">'+button('back','返回修改')+button('confirm','确认并保存新版本',true)+'</div></div>';
 action('back',async()=>{step=7;await save();await render();});action('confirm',async()=>{if(!document.getElementById('confirmed').checked)throw new Error('请先确认你的选择');await queue;const x=await api('sessions/'+session.id+'/confirm','POST',{expectedRevision:session.revision,confirmed:true});session=x.session;step=9;out=x.view;await render();});
}
async function result(){out=await api('sessions/'+session.id+'/view');app.innerHTML='<div class="card"><h2 id="result-title">侧写已保存 · 画像版本 '+out.UserProfile.revision+'</h2><p>这是'+(out.UserProfile.mode==='demo'?'演示模式':'本人填写')+'的求职需求。旧兴趣及人格分没有用于本次侧写。</p><label for="revision">查看已确认版本</label>'+select('revision',session.confirmedRevisions.map(n=>({id:String(n),text:'画像版本 '+n})),String(out.UserProfile.revision),'请选择版本')+'<p class="muted">修改后重新确认会生成新版本，旧版本保持不变。</p><div class="actions">'+button('analyze','继续分析岗位',true)+button('edit','修改当前选择')+button('new','开始新的判断')+'</div><p class="muted">需求已保存，可通过“继续上次的判断”找回。</p></div><div id="saved-description"></div>';
 // Render the selected immutable snapshot, never the possibly edited draft.
 function showSnapshot(){document.getElementById('result-title').textContent='侧写已保存 · 画像版本 '+out.UserProfile.revision;document.getElementById('saved-description').innerHTML=out.JobNeedsSnapshot.topics.map(t=>{const def=boot.catalog.topics.find(x=>x.id===t.topicId);return '<div class="card"><h3>'+esc(t.title)+'</h3><p>'+esc(boot.catalog.priorities.find(x=>x.id===t.priority)?.text??'暂不确定')+'</p><ul>'+(t.verificationItemIds.length?t.verificationItemIds.map(id=>'<li>'+esc(def.details.find(x=>x.id===id).text)+'</li>').join(''):'<li>关注项目暂不确定</li>')+'</ul><p>'+esc(boot.catalog.policies.find(x=>x.id===t.unknownHandling)?.text??'暂不确定')+'</p></div>';}).join('')+'<div class="card"><h3>现实条件</h3><ul>'+out.UserProfile.preferences.map(c=>'<li>'+conditionDescription(c)+'</li>').join('')+'</ul><h3>行业与岗位</h3><p>'+esc(out.SearchIntent.industryTags.map(id=>boot.industries.find(x=>x.id===id).name).join('、')||'行业暂不确定')+'</p><p>'+esc(out.SearchIntent.roleTypes.map(id=>boot.roles.find(x=>x.id===id).name).join('、')||'岗位暂不确定')+'</p></div>';}
 showSnapshot();document.getElementById('revision').addEventListener('change',async e=>{try{notice.textContent='';if(!e.target.value)return;out=await api('sessions/'+session.id+'/view?revision='+e.target.value);showSnapshot();}catch(x){error(x);}});
 action('analyze',async()=>{const returnTo=new URL(location.href).searchParams.get('returnTo');location.href=returnTo&&/^\/revise\/report-[a-zA-Z0-9-]{1,100}$/.test(returnTo)?returnTo:'/analyze?sessionId='+encodeURIComponent(session.id)+'&revision='+out.UserProfile.revision;});
 action('edit',async()=>{step=0;await save();await render();});action('new',async()=>{session=null;const u=new URL(location.href);u.searchParams.delete('sessionId');u.searchParams.set('new','1');history.replaceState(null,'',u);home();});
}
function locateSession(){const u=new URL(location.href);u.searchParams.delete('new');u.searchParams.delete('home');u.searchParams.set('sessionId',session.id);history.replaceState(null,'',u);for(const a of document.querySelectorAll('footer a'))if(a.textContent==='用需求分析一份JD')a.href='/analyze?sessionId='+encodeURIComponent(session.id);}
async function render(){app.onchange=null;nav();if(step<7)topicPage();else if(step===7)conditionsPage();else if(step===8)await review();else await result();window.scrollTo(0,0);}
try{boot=await api('bootstrap');const requested=new URL(location.href).searchParams.get('sessionId');const fresh=new URL(location.href).searchParams.get('new')==='1';const target=requested&&boot.sessions.some(s=>s.id===requested)?requested:fresh||new URL(location.href).searchParams.get('home')==='1'?null:boot.latestSessionId;if(target){session=await api('sessions/'+target);data=structuredClone(session.data);step=session.step;await render();}else home();}catch(e){error(e);app.textContent='无法读取本地会话，请检查服务器或刷新后重试。';}
