const app=document.querySelector('#app'),notice=document.querySelector('#notice'),steps=document.querySelector('#steps');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let boot,session=null,data,step=0,queue=Promise.resolve(),out;
async function api(path,method='GET',body){const r=await fetch('/api/a/needs/'+path,{method,headers:{'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const x=await r.json();if(!r.ok)throw new Error(x.error?.message??'请求失败');return x;}
function error(e){notice.textContent=e.message;}
function button(id,text,primary=false){return '<button id="'+id+'"'+(primary?' class="primary"':'')+'>'+text+'</button>';}
function action(id,fn){document.getElementById(id)?.addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;try{await fn();}catch(x){error(x);}finally{if(b.isConnected)b.disabled=false;}});}
function select(id,items,value,unknown='暂不确定'){return '<select id="'+id+'"><option value="">'+unknown+'</option>'+items.map(x=>'<option value="'+esc(x.id)+'"'+(String(value)===String(x.id)?' selected':'')+'>'+esc(x.text)+'</option>').join('')+'</select>';}
function save(){const snapshot=structuredClone(data),position=step;notice.textContent='正在保存…';queue=queue.then(async()=>{session=await api('sessions/'+session.id,'PATCH',{expectedRevision:session.revision,questionnaireVersion:boot.catalog.version,data:snapshot,step:position});notice.textContent='已自动保存';});return queue;}
function download(x,name,type='application/json'){const url=URL.createObjectURL(new Blob([typeof x==='string'?x:JSON.stringify(x,null,2)],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const checkOptions=(name,items,selected=[])=>'<div class="options">'+items.map(x=>'<label><input type="checkbox" name="'+name+'" value="'+esc(x.id)+'"'+(selected?.includes(x.id)?' checked':'')+'> '+esc(x.text)+'</label>').join('')+'</div>';
function nav(){steps.innerHTML=[...boot.catalog.topics.map(t=>t.title),'现实条件与方向','确认画像','保存与导出'].map((text,i)=>'<div'+(session&&i===step?' class="active"':'')+'>'+esc(text)+'</div>').join('');}
function home(){nav();app.innerHTML='<div class="card"><h2>先了解你的求职需求</h2><p>七个主题，每个主题三个选择问题。你可以跳过或选择“暂不确定”，之后再修改。</p><p class="muted">这里记录你的求职需求，不评估兴趣、人格或能力。</p>'+select('mode',[{id:'manual',text:'填写我的真实需求'},{id:'demo',text:'演示模式（数据明确标记）'}],'manual')+'<div class="actions">'+button('start','开始填写',true)+'</div><label for="import">恢复已导出的完整JSON</label><input id="import" type="file" accept="application/json,.json"><p class="muted">旧兴趣、人格问卷及历史答案保留存档，不转换成新需求。'+(boot.historicalRecordCount?'本会话有 '+boot.historicalRecordCount+' 条旧记录。':'')+'</p></div>';
 action('start',async()=>{session=await api('sessions','POST',{mode:document.getElementById('mode').value});data=structuredClone(session.data);step=0;await render();});
 document.getElementById('import').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>6000000)throw new Error('导入文件过大');session=await api('import','POST',JSON.parse(await file.text()));data=structuredClone(session.data);step=session.step;queue=Promise.resolve();await render();}catch(x){error(x);}});
}
function topicPage(){const t=boot.catalog.topics[step];app.innerHTML='<div class="card"><p class="muted">主题 '+(step+1)+' / 7</p><h2>'+esc(t.title)+'</h2><p>'+esc(t.description)+'</p>'+t.questions.map(q=>'<fieldset class="question"><legend>'+esc(q.text)+'</legend>'+(q.kind==='single'?'<div class="options">'+q.options.map(o=>'<label><input type="radio" name="'+q.id+'" value="'+o.id+'"'+(data.answers[q.id]===o.id?' checked':'')+'> '+esc(o.text)+'</label>').join('')+'</div>':checkOptions(q.id,q.options,data.answers[q.id]))+'</fieldset>').join('')+'<div class="actions">'+(step?button('back','上一页'):button('home','返回开始'))+button('next',step===6?'下一步：现实条件':'下一主题',true)+'</div></div>';
 for(const input of app.querySelectorAll('input'))input.addEventListener('change',async e=>{try{const q=e.target.name;if(e.target.type==='radio')data.answers[q]=e.target.value;else{const list=[...app.querySelectorAll('input')].filter(el=>el.name===q);if(e.target.value==='unsure'&&e.target.checked)list.filter(el=>el.value!=='unsure').forEach(el=>el.checked=false);else if(e.target.checked)list.find(el=>el.value==='unsure').checked=false;data.answers[q]=list.filter(el=>el.checked).map(el=>el.value);if(!data.answers[q].length)data.answers[q]=null;}await save();}catch(x){error(x);}});
 action('home',async()=>{await save();session=null;home();});action('back',async()=>{step--;await save();await render();});action('next',async()=>{step++;await save();await render();});
}
function conditionsPage(){
 const labels=boot.conditions.labels,city=data.conditions.find(c=>c.key==='city');
 const strengthSelect=c=>select(c.key+'-strength',[{id:'soft',text:'偏好，可结合其他条件考虑'},{id:'hard',text:'必须满足，由我明确确认'}],c.strength==='unknown'?null:c.strength,'未选择条件时保持未知');
 app.innerHTML='<div class="card"><h2>现实条件与行业、岗位方向</h2><p class="muted">只选必要条件。未选择的保持未知；“必须满足”仅在下一步由你确认后生效。</p><label for="stage">当前求职阶段</label>'+select('stage',boot.stages,data.stageId)+'<div id="goal-branch"></div><h3>希望工作带来的改善（可多选）</h3>'+checkOptions('expectations',boot.goals.filter(g=>boot.expectationIds.includes(g.id)),data.goalIds)+'<h3>目标行业（可多选）</h3>'+checkOptions('industries',boot.industries.map(x=>({id:x.id,text:x.name})),data.industryTags)+'<p class="muted">未选表示暂不确定；行业标签可能交叉，仅映射宽泛行业门类。</p><h3>岗位类型（可多选）</h3>'+checkOptions('roles',boot.roles.map(x=>({id:x.id,text:x.name})),data.roleTypes)+'<p class="muted">岗位标签是产品分类，不代表官方职业编码或能力判断。</p><div class="question"><h3>工作城市（可多选并排序）</h3><details id="city-choices"><summary>选择城市（可多选）</summary>'+checkOptions('cities',boot.conditions.cities.map(text=>({id:text,text})),city.value??[])+'</details><p class="muted">排序代表你的优先顺序，第一项最优先；用上移、下移调整。未选择表示暂不确定。</p><div id="city-order"></div>'+strengthSelect(city)+'</div>'+data.conditions.filter(c=>c.key!=='city').map(c=>'<div class="question"><label for="'+c.key+'">'+esc(labels[c.key])+'</label>'+select(c.key,c.key==='min_fixed_monthly_salary'?boot.conditions.salaries.map(n=>({id:String(n),text:'至少 '+n+' 元／月（人民币税前固定部分）'})):[{id:'true',text:'接受'},{id:'false',text:'不接受'}],c.value===null?null:String(c.value))+strengthSelect(c)+'</div>').join('')+'<div class="actions">'+button('back','上一页')+button('next','查看并确认侧写',true)+'</div></div>';
 function renderGoals(){
  const allowed=boot.goalBranches[data.stageId]??[],tasks=data.goalIds.filter(id=>boot.primaryGoalIds.includes(id)),valid=tasks.length===1&&allowed.includes(tasks[0]),selected=valid?tasks[0]:'';
  document.getElementById('goal-branch').innerHTML='<h3>当前求职任务（单选）</h3>'+(data.stageId?'<div class="options">'+boot.goals.filter(g=>allowed.includes(g.id)).concat([{id:'',text:'暂不确定'}]).map(g=>'<label><input type="radio" name="task" value="'+g.id+'"'+(selected===g.id?' checked':'')+'> '+esc(g.text)+'</label>').join('')+'</div>':'<p class="muted">先选择当前阶段，再显示对应任务；也可以暂不确定。</p>')+(tasks.length&&!valid?'<p class="muted">旧任务选择与当前分支不一致，请重新选择；原确认版本保留。</p>':'');
 }
 function renderCities(){const xs=data.conditions.find(c=>c.key==='city').value??[];document.getElementById('city-order').innerHTML=xs.length?'<ol>'+xs.map((name,i)=>'<li>'+esc(name)+' <button type="button" data-city-index="'+i+'" data-city-action="up" aria-label="提高'+esc(name)+'优先级"'+(!i?' disabled':'')+'>上移</button> <button type="button" data-city-index="'+i+'" data-city-action="down" aria-label="降低'+esc(name)+'优先级"'+(i===xs.length-1?' disabled':'')+'>下移</button></li>').join('')+'</ol>':'<p class="muted">城市暂不确定</p>';}
 renderGoals();renderCities();
 const selected=name=>[...app.querySelectorAll('input[type=checkbox]')].filter(x=>x.name===name&&x.checked).map(x=>x.value);
 app.onchange=async e=>{try{
  const oldStage=data.stageId;data.stageId=document.getElementById('stage').value||null;
  if(e.target.id==='stage'&&oldStage!==data.stageId){data.goalIds=data.goalIds.filter(id=>boot.expectationIds.includes(id)||(boot.goalBranches[data.stageId]??[]).includes(id));renderGoals();}
  const task=app.querySelector('input[name=task]:checked')?.value;
  data.goalIds=[...(task?[task]:[]),...selected('expectations')];data.industryTags=selected('industries');data.roleTypes=selected('roles');
  data.conditions=data.conditions.map(c=>{let value;if(c.key==='city'){const chosen=selected('cities'),before=c.value??[];const order=[...before.filter(name=>chosen.includes(name)),...chosen.filter(name=>!before.includes(name))];value=order.length?order:null;}else{const raw=document.getElementById(c.key).value;value=raw===''?null:c.key==='min_fixed_monthly_salary'?Number(raw):raw==='true';}let strength=document.getElementById(c.key+'-strength').value;if(value===null)strength='unknown';else if(!strength)strength='soft';document.getElementById(c.key+'-strength').value=strength==='unknown'?'':strength;return {key:c.key,value,strength};});
  if(e.target.name==='cities')renderCities();await save();
 }catch(x){error(x);}};
 document.getElementById('city-order').onclick=async e=>{const b=e.target.closest('button[data-city-action]');if(!b||b.disabled)return;try{const xs=data.conditions.find(c=>c.key==='city').value,index=Number(b.dataset.cityIndex),target=index+(b.dataset.cityAction==='up'?-1:1);if(target<0||target>=xs.length)return;[xs[index],xs[target]]=[xs[target],xs[index]];renderCities();await save();}catch(x){error(x);}};
 action('back',async()=>{step=6;await save();await render();});action('next',async()=>{step=8;await save();await render();});
}

function conditionDescription(c){const text=c.value===null?'暂不确定':c.key==='city'?c.value.join('、'):c.key==='min_fixed_monthly_salary'?'至少 '+c.value+' 元／月（人民币税前固定部分）':c.value?'接受':'不接受';return esc(boot.conditions.labels[c.key])+'：'+esc(text)+(c.strength==='hard'?'（必须满足）':c.strength==='soft'?'（偏好）':'');}
function descriptionHtml(description){return description.map(t=>'<div class="card"><h3>'+esc(t.title)+'</h3><p>'+esc(t.priority)+'</p><ul>'+t.details.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul><p>'+esc(t.policy)+'</p></div>').join('');}
async function review(){const p=await api('sessions/'+session.id+'/preview');app.innerHTML='<h2>确认你的求职需求侧写</h2><p class="muted">同一份答案生成页面与JSON。重点不代表硬约束，信息不清楚不代表企业有风险；未选信息保持未知。</p>'+descriptionHtml(p.description)+'<div class="card"><h3>现实条件</h3><ul>'+data.conditions.map(c=>'<li>'+conditionDescription(c)+'</li>').join('')+'</ul><h3>目标行业与岗位</h3><p>行业：'+esc(data.industryTags.map(id=>boot.industries.find(x=>x.id===id).name).join('、')||'暂不确定')+'</p><p>岗位：'+esc(data.roleTypes.map(id=>boot.roles.find(x=>x.id===id).name).join('、')||'暂不确定')+'</p><p class="muted">七主题侧写已在A内实现，B/C仍需对接这份附表。现有五类现实条件保留公共契约。</p><label class="check"><input type="checkbox" id="confirmed"> 我已检查以上选择；有值的现实条件及其“偏好／必须满足”设置由我确认，未知项保持未知。</label><div class="actions">'+button('back','返回修改')+button('confirm','确认并保存新版本',true)+'</div></div>';
 action('back',async()=>{step=7;await save();await render();});action('confirm',async()=>{if(!document.getElementById('confirmed').checked)throw new Error('请先确认你的选择');await queue;const x=await api('sessions/'+session.id+'/confirm','POST',{expectedRevision:session.revision,confirmed:true});session=x.session;step=9;out=x.export;await render();});
}
async function result(){out=await api('sessions/'+session.id+'/export');app.innerHTML='<div class="card"><h2 id="result-title">侧写已保存 · 画像版本 '+out.UserProfile.revision+'</h2><p>这是'+(out.UserProfile.mode==='demo'?'演示模式':'本人填写')+'的求职需求。旧兴趣及人格分没有用于本次侧写。</p><label for="revision">查看已确认版本</label>'+select('revision',session.confirmedRevisions.map(n=>({id:String(n),text:'画像版本 '+n})),String(out.UserProfile.revision),'请选择版本')+'<p class="muted">修改后重新确认会生成新版本，旧版本保持不变。</p><div class="actions">'+button('json','下载完整JSON',true)+button('markdown','下载侧写说明')+button('edit','修改当前选择')+button('new','新建一份侧写')+'</div><label for="restore">导入完整JSON</label><input id="restore" type="file" accept="application/json,.json"><p class="muted">'+esc(out.JobNeedsSnapshot.handoff.message)+'</p></div><div id="saved-description"></div>';
 // Render the selected immutable snapshot, never the possibly edited draft.
 function showSnapshot(){document.getElementById('result-title').textContent='侧写已保存 · 画像版本 '+out.UserProfile.revision;document.getElementById('saved-description').innerHTML=out.JobNeedsSnapshot.topics.map(t=>{const def=boot.catalog.topics.find(x=>x.id===t.topicId);return '<div class="card"><h3>'+esc(t.title)+'</h3><p>'+esc(boot.catalog.priorities.find(x=>x.id===t.priority)?.text??'暂不确定')+'</p><ul>'+(t.verificationItemIds.length?t.verificationItemIds.map(id=>'<li>'+esc(def.details.find(x=>x.id===id).text)+'</li>').join(''):'<li>关注项目暂不确定</li>')+'</ul><p>'+esc(boot.catalog.policies.find(x=>x.id===t.unknownHandling)?.text??'暂不确定')+'</p></div>';}).join('')+'<div class="card"><h3>现实条件</h3><ul>'+out.UserProfile.preferences.map(c=>'<li>'+conditionDescription(c)+'</li>').join('')+'</ul><h3>行业与岗位</h3><p>'+esc(out.SearchIntent.industryTags.map(id=>boot.industries.find(x=>x.id===id).name).join('、')||'行业暂不确定')+'</p><p>'+esc(out.SearchIntent.roleTypes.map(id=>boot.roles.find(x=>x.id===id).name).join('、')||'岗位暂不确定')+'</p></div>';}
 showSnapshot();document.getElementById('revision').addEventListener('change',async e=>{try{if(!e.target.value)return;out=await api('sessions/'+session.id+'/export?revision='+e.target.value);showSnapshot();}catch(x){error(x);}});
 action('json',async()=>download(out,'A-求职需求-画像版本'+out.UserProfile.revision+'.json'));
 action('markdown',async()=>download(out.Report.markdown,'A-求职需求-画像版本'+out.UserProfile.revision+'.md','text/markdown;charset=utf-8'));
 action('edit',async()=>{step=0;await save();await render();});action('new',async()=>{session=null;home();});
 document.getElementById('restore').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>6000000)throw new Error('导入文件过大');session=await api('import','POST',JSON.parse(await file.text()));data=structuredClone(session.data);step=9;queue=Promise.resolve();await render();}catch(x){error(x);}});
}
async function render(){app.onchange=null;nav();if(step<7)topicPage();else if(step===7)conditionsPage();else if(step===8)await review();else await result();window.scrollTo(0,0);}
try{boot=await api('bootstrap');if(boot.latestSessionId){session=await api('sessions/'+boot.latestSessionId);data=structuredClone(session.data);step=session.step;await render();}else home();}catch(e){error(e);app.textContent='无法读取本地会话，请检查服务器或刷新后重试。';}
