import {mountBattery} from './battery-survey.mjs';
const app=document.querySelector('#app'),notice=document.querySelector('#notice');
const steps=['开始','兴趣','结果与人格倾向','价值取舍','现实条件','审阅确认','职业方向与导出'];
let bank,s,widget,profile,fit,report,handoff,choices=[],queue=Promise.resolve(),navigationPending=false,draftTimer;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const checked=name=>[...document.querySelectorAll('input[name='+name+']:checked')].map(x=>x.value);
const choiceBoxes=(name,options,values)=>`<div class="options">${options.map(x=>`<label><input type="checkbox" name="${name}" id="${name}-${x.id}" value="${esc(x.text)}" ${values.includes(x.text)?'checked':''}> ${esc(x.text)}</label>`).join('')}</div>`;
const select=(id,label,options,value)=>`<label>${label}<select id="${id}"><option value="">不确定 / 暂不选择</option>${options.map(([v,t])=>`<option value="${esc(v)}" ${String(value??'')===String(v)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
const labels={realistic:'实践活动',investigative:'研究活动',artistic:'创作活动',social:'助人活动',enterprising:'经营与推动',conventional:'组织与记录',extraversion:'外向表达',agreeableness:'合作与体谅',conscientiousness:'条理与尽责',neuroticism:'情绪波动',intellect_imagination:'思维与想象倾向'};
async function api(path,method='GET',body){const r=await fetch('/api/a/v2/'+path,{method,headers:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const x=await r.json();if(!r.ok)throw new Error(`${x.error?.message??'请求失败'}（${x.error?.code??r.status}）`);return x;}
function run(fn){queue=queue.then(async()=>{try{await fn();}catch(e){notice.textContent=e.message;}});return queue;}
function on(id,fn){const el=document.getElementById(id);if(el)el.onclick=()=>{if(navigationPending)return;navigationPending=true;app.querySelectorAll('.actions button').forEach(x=>x.disabled=true);run(fn).finally(()=>{navigationPending=false;app.querySelectorAll('.actions button').forEach(x=>x.disabled=false);if(s?.step===6&&!handoff)for(const id of ['download-v2','download-v1','download-intent'])document.getElementById(id).disabled=true;});};}
const field=(id,label,value='',type='text')=>`<label>${label}<input id="${id}" type="${type}" value="${esc(value)}"></label>`;
const actions=(next='继续',back=true)=>`<div class="actions">${back?'<button id="back">上一步</button>':'<span></span>'}<button id="next" class="primary">${next}</button></div>`;
const tool=id=>bank.instruments.find(t=>t.instrumentId===id);
const assessmentSummary=a=>`<div class="card"><h3>${a.instrumentId==='onet-mini-ip'?'职业兴趣':'人格倾向'}</h3>${a.complete?a.scores.map(sc=>`<div class="score"><span>${labels[sc.dimension]}</span><progress max="100" value="${sc.normalized*100}"></progress><small>${sc.raw}/20 · 展示 ${(sc.normalized*100).toFixed(1)}</small></div>`).join(''):`<p>已答 ${Math.round(a.completeness*100)}%，未完成解释保持未知。</p>`}<p class="muted">量程展示分不是百分位、能力分或概率；没有高低阈值。源工具有研究依据；本次呈现语言：${esc(a.locale)}，翻译版本：${esc(a.translationVersion??'无')}。中文译稿与本产品未做心理测量验证。</p></div>`;
async function saveStep(step=s.step,draft=s.draft){s=await api('sessions/'+s.id,'PATCH',{expectedRevision:s.revision,step,draft});if(bank.privateTranslationPreview&&[1,2].includes(step)){const id=step===1?'onet-mini-ip':'mini-ipip',a=s.attempts[id];if(a&&a.locale!=='zh-CN')s=await api('attempts/'+a.id,'PATCH',{expectedRevision:s.revision,instrumentVersion:a.instrumentVersion,scoringVersion:a.scoringVersion,responses:[],locale:'zh-CN',translationVersion:tool(id).chineseDraft.translationVersion});}}
async function saveSurvey(){if(!widget)return;const id=s.step===1?'onet-mini-ip':'mini-ipip',a=s.attempts[id],snapshot=widget.capture();s=await api('attempts/'+a.id,'PATCH',{expectedRevision:s.revision,instrumentVersion:a.instrumentVersion,scoringVersion:a.scoringVersion,...snapshot});}
async function scoreCurrent(id){const a=s.attempts[id];if(!a)return;const x=await api('attempts/'+a.id+'/score','POST',{expectedRevision:s.revision});s=x.session;return x.snapshot;}
function captureDraft(){const d=structuredClone(s.draft);
 if(s.step===3){const groups=new Map();bank.valueOptions.forEach((value,i)=>{const rank=document.getElementById('value-'+i).value;if(rank){if(!groups.has(rank))groups.set(rank,[]);groups.get(rank).push(value);}});d.groups=[...groups].sort((a,b)=>Number(a[0])-Number(b[0])).map(([,g])=>g);d.tradeoffs=checked('tradeoff');}
 if(s.step===4){d.goals=checked('goal');d.jobStage=document.getElementById('stage').value||null;
  d.constraints=['city','min_fixed_monthly_salary','accept_sales_kpi','accept_travel','accept_outsourcing','work_schedule'].map(key=>{const el=document.getElementById(key),raw=key==='city'?[...el.selectedOptions].map(x=>x.value):el.value,strength=document.getElementById(key+'-strength').value;const empty=Array.isArray(raw)?!raw.length:raw==='';const value=strength==='unknown'||empty?null:key==='city'?raw:key==='min_fixed_monthly_salary'?Number(raw):key==='work_schedule'?raw:raw==='true';return {key,value,strength:value===null?'unknown':strength,confirmed:document.getElementById(key+'-confirmed').checked,evidenceIds:[]};});
 }return d;
}
async function loadFinal(){profile=await api('profiles/'+s.profileId+'?revision='+s.profileRevision);fit=await api('profiles/'+s.profileId+'/occupation-fit','POST',{profileRevision:profile.revision});report=await api('profiles/'+s.profileId+'/report?revision='+profile.revision);choices=fit.candidates.length?fit.candidates:(await api('catalog')).items.slice(0,20);handoff=s.intentProfileRevision===profile.revision?await api('profiles/'+s.profileId+'/export?revision='+profile.revision):null;}
function download(name,value,type='application/json'){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function render(){widget?.dispose();widget=null;notice.textContent='';const step=s?.step??0;
 document.querySelector('#steps').innerHTML=steps.map((t,i)=>`<div class="${step===i?'active':''}">${i+1} ${t}</div>`).join('');
 if(step===0)app.innerHTML=`<p class="eyebrow">CAREER PROFILE · V2</p><h2>先了解自己，再探索职业。</h2><p class="muted">测评完整保留原题与原计分；可以暂停或跳过，未知不会变成默认分。</p><div class="card"><label>整理路线<select id="battery"><option value="Standard">完整50题 · 30题职业兴趣＋20题人格倾向</option><option value="Quick">完整30题 · 职业兴趣</option><option value="None">暂不测评 · 从选择式需求与条件开始</option></select></label><p class="muted">${bank.privateTranslationPreview?'当前本机已开启中文译稿审校预览；两套题都以中文呈现，英文原文可展开核查。':'公开版本保留30题兴趣英文原文；20题人格提供未验证中文译稿。O*NET中文尚未公开发布。'}价值、取舍、目标与现实条件只需选择，不要求自由填写。</p><label>数据模式<select id="mode"><option value="manual">本人资料</option><option value="demo">合成演示</option></select></label><p class="muted">资料保存在本机服务，不自动发送给模型或其他模块。</p></div>${actions('开始',false)}<div class="card"><label>导入V2确认快照<input id="import" type="file" accept=".json"></label><p class="muted">导入校验当前选项；不重新计算缺少原始答案的分数。</p></div>`;
 if(step===1)app.innerHTML=`<p class="eyebrow">MINI-IP · 30</p><h2>哪些工作活动让你感兴趣？</h2><p class="muted">兴趣不是能力；按是否喜欢活动回答。“不确定”是数值2的有效答案；未答仍为缺答。</p>${bank.privateTranslationPreview?'<p class="muted">中文为本机审校译稿，尚未验证；原始题号、维度与0–4计分不变。</p>':''}<div id="survey"></div><div class="actions"><button id="back">上一步</button><button id="save">保存草稿</button><button id="skip">暂不完成</button><button id="next" class="primary">查看兴趣结果</button></div><p class="muted">O*NET® Career Exploration Tools · USDOL/ETA · <a href="https://www.onetcenter.org/dl_files/Mini-IP.pdf">2016原始题本与计分依据</a> · <a href="https://www.onetcenter.org/license_tools.html">工具许可</a>。</p>`;
 if(step===2){const a=s.attempts['onet-mini-ip']?.scoredSnapshot;app.innerHTML=`<p class="eyebrow">INTERESTS & WORK STYLE</p><h2>兴趣结果与平时的人格倾向。</h2>${a?assessmentSummary(a):''}${s.attempts['mini-ipip']?`<div class="card"><h3>Mini-IPIP · 20题（中文译稿未验证）</h3><p class="muted">描述平时的自己，无需选择显得优秀的答案。神经质维度表示情绪波动方向，不用于淘汰岗位。各维度独立展示，不能作为能力判断。</p><label>题目语言<select id="presentation-locale"><option value="zh-CN" ${s.attempts['mini-ipip'].locale==='zh-CN'?'selected':''}>中文译稿（未验证）</option><option value="en" ${s.attempts['mini-ipip'].locale!=='zh-CN'?'selected':''}>英文原文</option></select></label><div id="survey"></div><p class="muted"><a href="https://ipip.ori.org/MiniIPIPKey.htm">官方key</a> · <a href="https://ipip.ori.org/newPermission.htm">IPIP题目公共领域</a>。题目按官方key顺序展示。</p></div><div class="actions"><button id="back">上一步</button><button id="save">保存草稿</button><button id="skip">暂不完成</button><button id="next" class="primary">保存并继续</button></div>`:actions()}`;}
 if(step===3){const d=s.draft;app.innerHTML=`<p class="eyebrow">YOUR DECLARED PRIORITIES</p><h2>当前求职，哪些事情更重要？</h2><p class="muted">这是本人偏好表达，不是工作价值观量表。只选择预设选项，允许同级与不确定；1级优先于2级，不合成价值观分数。</p><div class="grid card">${bank.valueOptions.map((v,i)=>{const rank=d.groups.findIndex(g=>g.includes(v));return `<label>${v}<select id="value-${i}"><option value="">不确定 / 暂不排序</option>${[1,2,3,4,5].map(n=>`<option value="${n}" ${rank===n-1?'selected':''}>${n}级优先</option>`).join('')}</select></label>`;}).join('')}</div><div class="card"><h3>目前可以接受哪些取舍？</h3><p class="muted">可多选；都不选择表示尚不确定。仅记录你的声明，不推断风险承受能力。</p>${choiceBoxes('tradeoff',bank.selectionCatalog.tradeoffs,d.tradeoffs)}</div>${actions()}`;}
 if(step===4){const d=s.draft,control=(key,title,input)=>{const c=d.constraints.find(c=>c.key===key);return `<div class="card"><h3>${title}</h3>${input}<label>要求程度<select id="${key}-strength">${[['unknown','尚不确定'],['soft','软偏好'],['hard','硬条件']].map(([v,t])=>`<option value="${v}" ${c?.strength===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="check"><input id="${key}-confirmed" type="checkbox" ${c?.confirmed?'checked':''}> 我明确确认这项要求</label></div>`;};const value=key=>d.constraints.find(c=>c.key===key)?.value;const c=bank.selectionCatalog;
  app.innerHTML=`<p class="eyebrow">REALITY & GOALS</p><h2>选择本次求职的目标和现实条件。</h2><p class="muted">只需要选择。未选或未确认保持未知；下列选项不是量表题，不生成测评分数。</p><div class="card">${select('stage','当前阶段',c.stages.map(x=>[x.text,x.text]),d.jobStage)}<h3>当前目标（可多选）</h3>${choiceBoxes('goal',c.goals,d.goals)}</div>${control('city','城市',`<label>目标城市（可多选；按住Ctrl可选择多个）<select id="city" multiple size="5">${c.cities.map(v=>`<option value="${esc(v)}" ${(value('city')??[]).includes(v)?'selected':''}>${esc(v)}</option>`).join('')}</select></label><small>不选择表示暂不确定；本轮不设置“其他城市”的文字输入。</small>`)}${control('min_fixed_monthly_salary','最低固定月薪',select('min_fixed_monthly_salary','人民币税前固定月薪；不含奖金与佣金',c.salaries.map(v=>[v,'至少 '+v.toLocaleString()+' 元 / 月']),value('min_fixed_monthly_salary')))}${[['accept_sales_kpi','销售KPI'],['accept_travel','出差'],['accept_outsourcing','外包用工']].map(([key,title])=>control(key,title,select(key,'是否接受',[['true','接受'],['false','不接受']],value(key)))).join('')}${control('work_schedule','工作时段',select('work_schedule','工作时段要求',c.schedules.map(x=>[x.value,x.text]),value('work_schedule')))}${actions('审阅画像')}`;
 }
 if(step===5)app.innerHTML=`<p class="eyebrow">REVIEW BEFORE FREEZING</p><h2>确认属于你的这版画像。</h2>${Object.values(s.attempts).filter(a=>a.scoredSnapshot).map(a=>assessmentSummary(a.scoredSnapshot)).join('')}${s.insights.map((i,n)=>`<div class="card"><strong>解释草稿 · ${i.status==='pending'?'待确认':i.status==='confirmed'?'已确认':'已拒绝'}</strong><p>${esc(i.userEditedText??i.text)}</p><div class="claim-actions"><button data-insight="${n}" data-status="confirmed">确认解释</button><button data-insight="${n}" data-status="rejected">拒绝解释</button></div><small>拒绝解释不删除测评原始分。</small></div>`).join('')}<div class="card"><h3>本人价值偏好</h3><p>${esc(s.draft.groups.map((g,i)=>`${i+1}级：${g.join('、')}`).join('；')||'尚未声明')}</p><h3>目标与条件</h3><p>${esc(s.draft.goals.join('；')||'尚未声明')}</p>${s.draft.constraints.map(c=>`<p>${esc(bank.selectionCatalog.conditionLabels[c.key]??c.key)}：${esc(c.confirmed?JSON.stringify(c.value):'未确认 / 未知')} · ${c.confirmed?c.strength:'unknown'}</p>`).join('')}${s.selectionResetRequired?'<label class="check"><input id="confirm-choice-reset" type="checkbox"> 旧自由填写内容已存档，本次按当前选项重新选择，不自动带入旧要求。</label>':''}<label class="check"><input id="confirm" type="checkbox"> 我已核对；保存不可变确认版本。之后更正会生成新版本。</label></div>${actions('确认并探索方向')}`;
 if(step===6)app.innerHTML=`<p class="eyebrow">EXPLORE & HAND OFF</p><h2>值得进一步了解的方向。</h2><p class="muted">画像版本 ${profile.revision} · ${s.mode}。${fit.status==='ranked'?'兴趣形状相关排序；不是录用概率。':fit.status==='undifferentiated_profile'?'目前兴趣尚未区分，不生成排名。可以自主浏览。':'没有完整兴趣测评，不生成排名。可以自主浏览。'} ${fit.catalogCounts.loaded}个目录项中，${fit.catalogCounts.complete}个有完整六维。</p><label>浏览职业（英文标题或O*NET代码）<input id="career-search" placeholder="例如 Software、Designer"></label><button id="search-careers">搜索</button><div id="direction-list">${directionTiles()}</div><div class="card">${field('custom-direction','也可以自行填写一个方向，不虚构O*NET分数',handoff?.SearchIntentV2.selectedDirections.find(d=>!d.onetCodes.length)?.roleFamily??'')}<p class="muted">最多选3个方向。O*NET®为美国职业参考，国内JD映射待核查；没有自动判断真实岗位或公司。</p><button id="confirm-directions" class="primary">确认本次搜索方向</button><p>${handoff?'搜索意向已保存，可导出。':'先确认方向，再导出交接文件；也可确认暂不确定。'}</p></div><div class="card"><h3>你的可读画像</h3>${report.sections.map(section=>`<details><summary>${esc(section.title)}</summary>${section.claims.map(c=>`<p>${esc(c.text)}</p>${c.evidenceIds.length?`<small>依据：${c.evidenceIds.map(id=>{const e=report.evidence.find(e=>e.evidenceId===id);return esc(e?.text??e?.locator??id);}).join('；')}</small>`:''}`).join('')}</details>`).join('')}<button id="download-report">下载可读报告</button></div><div class="actions"><button id="download-v2" ${handoff?'':'disabled'}>下载V2 JSON</button><button id="download-intent" ${handoff?'':'disabled'}>仅下载SearchIntentV2</button><button id="download-v1" ${handoff?'':'disabled'}>兼容导出v1</button></div><p class="muted">V2包含测评与本人偏好依据，原始答案保存在本机；不采集或导出能力与经历。v1会明确说明未传递的字段；不能表达的硬条件会拒绝降级。</p><div class="actions">${s.imported?'':'<button id="edit">修改并创建新版本</button>'}<button id="new">新建画像</button><button id="delete">删除本人的此项目</button></div>`;
 if(bank.privateTranslationPreview)app.insertAdjacentHTML('afterbegin','<p class="muted">本机私有中文译稿审校预览 · 未经中文验证 · 不属于公开发布版</p>');
 bind();if((step===1&&s.attempts['onet-mini-ip'])||(step===2&&s.attempts['mini-ipip'])){
  const id=step===1?'onet-mini-ip':'mini-ipip',sessionId=s.id;widget=mountBattery(document.getElementById('survey'),tool(id),s.attempts[id],()=>{const snapshot=widget.capture();run(async()=>{if(s.id!==sessionId||s.step!==step)return;const a=s.attempts[id];s=await api('attempts/'+a.id,'PATCH',{expectedRevision:s.revision,instrumentVersion:a.instrumentVersion,scoringVersion:a.scoringVersion,...snapshot});notice.textContent='已自动保存';});},()=>document.getElementById('next').click());
  if(s.attempts[id].locale==='zh-CN'){const details=document.createElement('details');details.id='question-originals';details.innerHTML='<summary>展开英文原文与来源</summary><ol>'+tool(id).items.map(q=>'<li>'+esc(q.originalText)+'</li>').join('')+'</ol>';document.getElementById('survey').after(details);}
 }
}
function directionTiles(){const selected=handoff?.SearchIntentV2.selectedDirections.flatMap(d=>d.onetCodes)??[];return choices.map(c=>`<label class="tile"><input name="direction" type="checkbox" value="${c.onetCode}" ${selected.includes(c.onetCode)?'checked':''}> <strong>${esc(c.titleZh?c.titleZh+' / '+c.title:c.title)}</strong><small>${c.onetCode}${c.pearsonR===undefined||c.pearsonR===null?'':` · r=${c.pearsonR.toFixed(4)} · 并列位次 ${c.rank}`}</small><small>${esc(c.description)}</small><a href="${c.sourceUrl}" target="_blank" rel="noopener">职业参考来源</a></label>`).join('');}
async function proceed(allowIncomplete=false){clearTimeout(draftTimer);const step=s?.step??0;
 if(step===0){s=await api('sessions','POST',{battery:document.getElementById('battery').value,mode:document.getElementById('mode').value});await saveStep(s.battery==='None'?3:1);}
 else if(step===1||step===2&&s.attempts['mini-ipip']){await saveSurvey();const result=await scoreCurrent(step===1?'onet-mini-ip':'mini-ipip');if(!result.complete&&!allowIncomplete)throw new Error('请完成整套题本，或选择“暂不完成”；草稿已保存。');await saveStep(step+1);}
 else if(step===5){if(!document.getElementById('confirm').checked)throw new Error('请勾选本人确认');const x=await api('profiles/'+s.profileId+'/confirm','POST',{expectedRevision:s.revision,confirmed:true,selectionResetConfirmed:document.getElementById('confirm-choice-reset')?.checked??false});s=x.session;profile=x.profile;await saveStep(6);await loadFinal();}
 else{await saveStep(step+1,captureDraft());}render();
}
function bind(){on('next',()=>proceed());on('skip',()=>proceed(true));on('save',async()=>{await saveSurvey();notice.textContent='已保存，刷新可恢复。';});on('back',async()=>{if(widget)await saveSurvey();await saveStep(s.step===3&&s.battery==='None'?0:s.step-1,captureDraft());render();});
 document.querySelectorAll('[data-insight]').forEach(button=>button.onclick=()=>run(async()=>{const index=Number(button.dataset.insight),c=s.insights[index];s=await api('insights/'+c.insightId,'PATCH',{expectedRevision:s.revision,status:button.dataset.status});render();}));
 on('search-careers',async()=>{choices=(await api('catalog?q='+encodeURIComponent(document.getElementById('career-search').value))).items;document.getElementById('direction-list').innerHTML=directionTiles();});
 on('confirm-directions',async()=>{const selectedCodes=[...document.querySelectorAll('[name=direction]:checked')].map(x=>x.value);const x=await api('search-intents','POST',{expectedRevision:s.revision,profileId:s.profileId,profileRevision:profile.revision,selectedCodes,customDirection:document.getElementById('custom-direction').value,maxCandidates:3});s=x.session;handoff=await api('profiles/'+s.profileId+'/export?revision='+profile.revision);render();notice.textContent='搜索意向已保存。';});
 on('download-v2',()=>download('xray-profile-bundle-v2.json',handoff));on('download-intent',()=>download('xray-search-intent-v2.json',handoff.SearchIntentV2));
 on('download-v1',async()=>{const x=await api('profiles/'+s.profileId+'/export?revision='+profile.revision+'&format=v1');download('xray-v1-with-compatibility-warnings.json',x);notice.textContent=x.compatibilityWarnings.join(' ');});
 on('download-report',async()=>{const x=await api('profiles/'+s.profileId+'/report?revision='+profile.revision+'&format=markdown');download('xray-a-report-v'+profile.revision+'.md',x.markdown,'text/markdown');});
 on('edit',async()=>{await saveStep(4);render();});on('new',()=>{s=null;profile=null;handoff=null;render();});
 on('delete',async()=>{if(!confirm('删除此活动项目？历史rubbish存档和此前私有上传文件保留。'))return;await api('profiles/'+s.profileId,'DELETE',{});s=null;render();});
 const language=document.getElementById('presentation-locale');if(language)language.onchange=()=>{const locale=language.value;run(async()=>{await saveSurvey();const a=s.attempts['mini-ipip'];s=await api('attempts/'+a.id,'PATCH',{expectedRevision:s.revision,instrumentVersion:a.instrumentVersion,scoringVersion:a.scoringVersion,responses:[],locale,translationVersion:locale==='zh-CN'?tool('mini-ipip').chineseDraft.translationVersion:null});render();});};
 const importer=document.getElementById('import');if(importer)importer.onchange=()=>run(async()=>{const file=importer.files[0];if(file.size>6000000)throw new Error('导入文件过大');s=await api('import','POST',JSON.parse(await file.text()));await loadFinal();render();});
}
app.addEventListener('change',event=>{if(s?.step===4&&['city','min_fixed_monthly_salary','accept_sales_kpi','accept_travel','accept_outsourcing','work_schedule'].includes(event.target.id)){const known=event.target.multiple?event.target.selectedOptions.length>0:event.target.value!=='';const strength=document.getElementById(event.target.id+'-strength');if(known&&strength.value==='unknown')strength.value='soft';if(!known){strength.value='unknown';document.getElementById(event.target.id+'-confirmed').checked=false;}}});
app.addEventListener('input',event=>{if(!s||!([3,4].includes(s.step))||navigationPending)return;clearTimeout(draftTimer);const step=s.step,id=s.id;draftTimer=setTimeout(()=>{if(s?.id!==id||s.step!==step||navigationPending)return;const d=captureDraft();run(async()=>{if(s?.id!==id||s.step!==step)return;await saveStep(step,d);notice.textContent='已自动保存';});},350);});
await run(async()=>{bank=await api('bootstrap');s=bank.sessions.sort((a,b)=>a.updatedAt.localeCompare(b.updatedAt)).at(-1);if(bank.privateTranslationPreview&&s&&!s.imported&&s.step<=2){for(const [id,a] of Object.entries(s.attempts)){if(a.locale==='zh-CN')continue;s=await api('attempts/'+a.id,'PATCH',{expectedRevision:s.revision,instrumentVersion:a.instrumentVersion,scoringVersion:a.scoringVersion,responses:[],locale:'zh-CN',translationVersion:tool(id).chineseDraft.translationVersion});}}if(s?.step===6)await loadFinal();render();});
