import {mountBattery} from './battery-survey.mjs';
const app=document.querySelector('#app'),notice=document.querySelector('#notice');
const steps=['开始','兴趣','结果与工作方式','价值取舍','经历证据','现实条件','审阅确认','职业方向与导出'];
let bank,s,widget,profile,fit,report,handoff,choices=[],queue=Promise.resolve(),navigationPending=false,draftTimer;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines=x=>String(x??'').split(/[\n，,]+/).map(x=>x.trim()).filter(Boolean);
const labels={realistic:'实践活动',investigative:'研究活动',artistic:'创作活动',social:'助人活动',enterprising:'经营与推动',conventional:'组织与记录',extraversion:'外向表达',agreeableness:'合作与体谅',conscientiousness:'条理与尽责',neuroticism:'情绪波动',intellect_imagination:'智力／想象'};
async function api(path,method='GET',body){const r=await fetch('/api/a/v2/'+path,{method,headers:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const x=await r.json();if(!r.ok)throw new Error(`${x.error?.message??'请求失败'}（${x.error?.code??r.status}）`);return x;}
function run(fn){queue=queue.then(async()=>{try{await fn();}catch(e){notice.textContent=e.message;}});return queue;}
function on(id,fn){const el=document.getElementById(id);if(el)el.onclick=()=>{if(navigationPending)return;navigationPending=true;app.querySelectorAll('.actions button').forEach(x=>x.disabled=true);run(fn).finally(()=>{navigationPending=false;app.querySelectorAll('.actions button').forEach(x=>x.disabled=false);if(s?.step===7&&!handoff)for(const id of ['download-v2','download-v1','download-intent'])document.getElementById(id).disabled=true;});};}
const field=(id,label,value='',type='text')=>`<label>${label}<input id="${id}" type="${type}" value="${esc(value)}"></label>`;
const area=(id,label,value='')=>`<label>${label}<textarea id="${id}" rows="3">${esc(value)}</textarea></label>`;
const actions=(next='继续',back=true)=>`<div class="actions">${back?'<button id="back">上一步</button>':'<span></span>'}<button id="next" class="primary">${next}</button></div>`;
const tool=id=>bank.instruments.find(t=>t.instrumentId===id);
const assessmentSummary=a=>`<div class="card"><h3>${a.instrumentId==='onet-mini-ip'?'职业兴趣':'工作方式'}</h3>${a.complete?a.scores.map(sc=>`<div class="score"><span>${labels[sc.dimension]}</span><progress max="100" value="${sc.normalized*100}"></progress><small>${sc.raw}/20 · 展示 ${(sc.normalized*100).toFixed(1)}</small></div>`).join(''):`<p>已答 ${Math.round(a.completeness*100)}%，未完成解释保持未知。</p>`}<p class="muted">量程展示分不是百分位、能力分或概率；没有高低阈值。英文源工具有研究依据，中文与本产品未做心理测量验证。</p></div>`;
async function saveStep(step=s.step,draft=s.draft){s=await api('sessions/'+s.id,'PATCH',{expectedRevision:s.revision,step,draft});}
async function saveSurvey(){if(!widget)return;const id=s.step===1?'onet-mini-ip':'mini-ipip',a=s.attempts[id],snapshot=widget.capture();s=await api('attempts/'+a.id,'PATCH',{expectedRevision:s.revision,instrumentVersion:a.instrumentVersion,scoringVersion:a.scoringVersion,...snapshot});}
async function scoreCurrent(id){const a=s.attempts[id];if(!a)return;const x=await api('attempts/'+a.id+'/score','POST',{expectedRevision:s.revision});s=x.session;return x.snapshot;}
function captureDraft(){const d=structuredClone(s.draft);
 if(s.step===4)d.statementBuffer=document.getElementById('statement').value;
 if(s.step===3){const groups=new Map();bank.valueOptions.forEach((value,i)=>{const rank=document.getElementById('value-'+i).value;if(rank){if(!groups.has(rank))groups.set(rank,[]);groups.get(rank).push(value);}});d.groups=[...groups].sort((a,b)=>Number(a[0])-Number(b[0])).map(([,g])=>g);const custom=lines(document.getElementById('custom-values').value);if(custom.length)d.groups.push(custom);d.tradeoffs=lines(document.getElementById('tradeoffs').value);}
 if(s.step===5){d.goals=lines(document.getElementById('goals').value);d.jobStage=document.getElementById('stage').value||null;
  const keys=['city','min_fixed_monthly_salary','accept_sales_kpi','accept_travel','accept_outsourcing'];d.constraints=keys.map(key=>{const raw=document.getElementById(key).value,strength=document.getElementById(key+'-strength').value;const value=strength==='unknown'||raw===''?null:key==='city'?lines(raw):key==='min_fixed_monthly_salary'?Number(raw):raw==='true';return {key,value,strength:value===null||Array.isArray(value)&&!value.length?'unknown':strength,confirmed:document.getElementById(key+'-confirmed').checked,evidenceIds:[]};});
  const extraKey=document.getElementById('extra-key').value.trim(),extraValue=document.getElementById('extra-value').value.trim();if(extraKey&&extraValue)d.constraints.push({key:extraKey,value:extraValue,strength:document.getElementById('extra-strength').value,confirmed:document.getElementById('extra-confirmed').checked,evidenceIds:[]});
 }return d;
}
async function loadFinal(){profile=await api('profiles/'+s.profileId+'?revision='+s.profileRevision);fit=await api('profiles/'+s.profileId+'/occupation-fit','POST',{profileRevision:profile.revision});report=await api('profiles/'+s.profileId+'/report?revision='+profile.revision);choices=fit.candidates.length?fit.candidates:(await api('catalog')).items.slice(0,20);handoff=s.intentProfileRevision===profile.revision?await api('profiles/'+s.profileId+'/export?revision='+profile.revision):null;}
function download(name,value,type='application/json'){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function render(){widget?.dispose();widget=null;notice.textContent='';const step=s?.step??0;
 document.querySelector('#steps').innerHTML=steps.map((t,i)=>`<div class="${step===i?'active':''}">${i+1} ${t}</div>`).join('');
 if(step===0)app.innerHTML=`<p class="eyebrow">CAREER PROFILE · V2</p><h2>先了解自己，再探索职业。</h2><p class="muted">每完成一层都能看到新增信息；可以暂停或跳过，未知不会变成默认分。</p><div class="card"><label>整理路线<select id="battery"><option value="Quick">Quick · 完整30题兴趣</option><option value="Standard">Standard · 30题兴趣＋20题工作方式</option><option value="None">暂不测评 · 从本人偏好与经历开始</option></select></label><p class="muted">测评题文保持官方英文，当前没有可直接使用的经验证中文题本。Standard另外包含偏好与经历确认，不承诺固定5分钟完成。题目测自报倾向，不证明实际能力。</p><label>数据模式<select id="mode"><option value="manual">本人资料</option><option value="demo">合成演示</option></select></label><p class="muted">资料保存在本地服务，不自动发送给模型或其他模块。</p></div>${actions('开始',false)}<div class="card"><label>导入V2确认快照<input id="import" type="file" accept=".json"></label><p class="muted">不会重算缺少原始答案的导入快照。原v1记录仍可从左侧入口查看。</p></div>`;
 if(step===1)app.innerHTML=`<p class="eyebrow">MINI-IP · OFFICIAL ENGLISH · 30</p><h2>哪些工作活动让你感兴趣？</h2><p class="muted">兴趣不是能力；按是否喜欢活动回答。Unsure=有效中间答案。看不懂的题目请留待补答，不默认选Unsure。</p><div id="survey"></div><div class="actions"><button id="back">上一步</button><button id="save">保存草稿</button><button id="skip">暂不完成</button><button id="next" class="primary">查看兴趣结果</button></div><p class="muted">O*NET® Career Exploration Tools · USDOL/ETA · <a href="https://www.onetcenter.org/dl_files/Mini-IP.pdf">2016原始题本</a> · <a href="https://www.onetcenter.org/license_tools.html">工具许可</a>。题文未翻译或改写。</p>`;
 if(step===2){const a=s.attempts['onet-mini-ip']?.scoredSnapshot;app.innerHTML=`<p class="eyebrow">INTERESTS & WORK STYLE</p><h2>兴趣结果与平时的工作方式。</h2>${a?assessmentSummary(a):''}${s.attempts['mini-ipip']?`<div class="card"><h3>Mini-IPIP · 官方英文20题</h3><p class="muted">描述平时的自己，无需选择显得优秀的答案。神经质维度表示情绪波动方向，不用于淘汰岗位。各维度独立展示，不能作为能力判断。</p><div id="survey"></div><p class="muted"><a href="https://ipip.ori.org/MiniIPIPKey.htm">官方key</a> · <a href="https://ipip.ori.org/newPermission.htm">IPIP题目公共领域</a>。题目按官方key顺序展示。</p></div><div class="actions"><button id="back">上一步</button><button id="save">保存草稿</button><button id="skip">暂不完成</button><button id="next" class="primary">保存并继续</button></div>`:actions()}`;}
 if(step===3){const d=s.draft;app.innerHTML=`<p class="eyebrow">YOUR DECLARED PRIORITIES</p><h2>当前求职，哪些事情更重要？</h2><p class="muted">这是本人偏好表达，不是工作价值观量表。允许同级、不确定与自定义；1级优先于2级。</p><div class="grid card">${bank.valueOptions.map((v,i)=>{const rank=d.groups.findIndex(g=>g.includes(v));return `<label>${v}<select id="value-${i}"><option value="">不确定 / 暂不排序</option>${[1,2,3,4,5].map(n=>`<option value="${n}" ${rank===n-1?'selected':''}>${n}级优先</option>`).join('')}</select></label>`;}).join('')}</div><div class="card">${area('custom-values','自定义偏好（同级，每行一项）',d.groups.flat().filter(v=>!bank.valueOptions.includes(v)).join('\n'))}${area('tradeoffs','可以接受的取舍（可留空）',d.tradeoffs.join('\n'))}</div>${actions()}`;}
 if(step===4)app.innerHTML=`<p class="eyebrow">EXPERIENCE WITH EVIDENCE</p><h2>复用简历，逐条核对经历。</h2><p class="muted">PDF/DOCX先提取文字，扫描件或图片使用本地OCR。每项保留原句，提取只是候选，不证明经历真实性。</p><div class="card"><label>上传简历<input id="resume-file" type="file" accept=".pdf,.docx,.png,.jpg,.jpeg"></label><p class="muted">单文件10MB，PDF最多30页；当前OCR${bank.ocrConnected?'本地模型已安装':'未配置，扫描件会明确提示，可改为手填'}。不用上传联系方式。</p><button id="upload">提取待确认条目</button>${area('statement','没有简历？写一句做过的事，或分行写学历、专业、技能和经历。',s.draft.statementBuffer??'')}<button id="extract-statement">生成待确认条目</button></div><div id="claims">${s.claims.map((c,index)=>{const e=s.evidence.find(e=>e.evidenceId===c.evidenceIds[0]);return `<div class="card"><p><strong>${c.status==='pending'?'待确认':c.status==='confirmed'?'已确认':'已拒绝'}</strong> · ${esc(e?.locator)}</p><blockquote>${esc(e?.text)}</blockquote><label>记录类别<select id="kind-${index}">${[['education','学历'],['major','专业'],['skill','技能陈述'],['experience','项目 / 实习 / 工作经历']].map(([v,t])=>`<option value="${v}" ${c.kind===v?'selected':''}>${t}</option>`).join('')}</select></label>${area('claim-'+index,'核对或修正原意',c.description)}<div class="claim-actions"><button data-claim="${index}" data-status="confirmed">确认此项</button><button data-claim="${index}" data-status="rejected">拒绝此项</button></div></div>`;}).join('')||'<p class="muted">可以不提供经历，此时能力保持未知。</p>'}</div>${actions()}`;
 if(step===5){const d=s.draft,control=(key,title,input)=>{const c=d.constraints.find(c=>c.key===key);return `<div class="card"><h3>${title}</h3>${input}<label>要求程度<select id="${key}-strength">${[['unknown','尚不确定'],['soft','软偏好'],['hard','硬条件']].map(([v,t])=>`<option value="${v}" ${c?.strength===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="check"><input id="${key}-confirmed" type="checkbox" ${c?.confirmed?'checked':''}> 我明确确认这项要求</label></div>`;};const extra=d.constraints.find(c=>!['city','min_fixed_monthly_salary','accept_sales_kpi','accept_travel','accept_outsourcing'].includes(c.key));
  app.innerHTML=`<p class="eyebrow">REALITY & GOALS</p><h2>只补充本次决策需要的信息。</h2><div class="card"><label>当前阶段<select id="stage"><option value="">不确定</option>${['探索方向','寻找实习','应届求职','转岗 / 换工作'].map(v=>`<option ${d.jobStage===v?'selected':''}>${v}</option>`).join('')}</select></label>${area('goals','当前目标（可留空）',d.goals.join('\n'))}</div>${control('city','城市',field('city','目标城市，允许多选或未知',(d.constraints.find(c=>c.key==='city')?.value??[]).join('，')))}${control('min_fixed_monthly_salary','薪资',field('min_fixed_monthly_salary','最低税前固定月薪，人民币；奖金与佣金不包含',d.constraints.find(c=>c.key==='min_fixed_monthly_salary')?.value??'','number'))}<details><summary>补充销售指标、出差与用工条件（按需）</summary>${[['accept_sales_kpi','销售KPI'],['accept_travel','出差'],['accept_outsourcing','外包用工']].map(([key,title])=>control(key,title,`<select id="${key}"><option value="">不确定</option>${[['true','接受'],['false','不接受']].map(([v,t])=>`<option value="${v}" ${String(d.constraints.find(c=>c.key===key)?.value)===v?'selected':''}>${t}</option>`).join('')}</select>`)).join('')}</details><details ${extra?'open':''}><summary>补充其他条件</summary><div class="card">${field('extra-key','条件名称（例如 work_schedule）',extra?.key)}${field('extra-value','本人要求',extra?.value)}<label>程度<select id="extra-strength"><option value="soft" ${extra?.strength==='soft'?'selected':''}>软偏好</option><option value="hard" ${extra?.strength==='hard'?'selected':''}>硬条件</option></select></label><label class="check"><input id="extra-confirmed" type="checkbox" ${extra?.confirmed?'checked':''}> 我明确确认</label></div></details>${actions('审阅画像')}`;
 }
 if(step===6)app.innerHTML=`<p class="eyebrow">REVIEW BEFORE FREEZING</p><h2>确认属于你的这版画像。</h2>${Object.values(s.attempts).filter(a=>a.scoredSnapshot).map(a=>assessmentSummary(a.scoredSnapshot)).join('')}${s.insights.map((i,n)=>`<div class="card"><strong>解释草稿 · ${i.status==='pending'?'待确认':i.status==='confirmed'?'已确认':'已拒绝'}</strong>${area('insight-'+n,'核对、编辑或拒绝解释',i.userEditedText??i.text)}<div class="claim-actions"><button data-insight="${n}" data-status="confirmed">确认解释</button><button data-insight="${n}" data-status="rejected">拒绝解释</button></div><small>拒绝解释不删除测评原始分。</small></div>`).join('')}<div class="card"><h3>本人价值偏好</h3><p>${esc(s.draft.groups.map((g,i)=>`${i+1}级：${g.join('、')}`).join('；')||'尚未声明')}</p><h3>经历</h3>${s.claims.filter(c=>c.status==='confirmed').map(c=>`<p>${esc(c.description)}</p>`).join('')||'<p>未提供确认经历，能力保持未知。</p>'}<h3>目标与条件</h3><p>${esc(s.draft.goals.join('；')||'尚未声明')}</p>${s.draft.constraints.map(c=>`<p>${esc(c.key)}：${esc(c.confirmed?JSON.stringify(c.value):'未确认 / 未知')} · ${c.confirmed?c.strength:'unknown'}</p>`).join('')}<label class="check"><input id="confirm" type="checkbox"> 我已核对；保存不可变确认版本。之后更正会生成新版本。</label></div>${actions('确认并探索方向')}`;
 if(step===7)app.innerHTML=`<p class="eyebrow">EXPLORE & HAND OFF</p><h2>值得进一步了解的方向。</h2><p class="muted">画像版本 ${profile.revision} · ${s.mode}。${fit.status==='ranked'?'兴趣形状相关排序；不是录用概率。':fit.status==='undifferentiated_profile'?'目前兴趣尚未区分，不生成排名。可以自主浏览。':'没有完整兴趣测评，不生成排名。可以自主浏览。'} ${fit.catalogCounts.loaded}个目录项中，${fit.catalogCounts.complete}个有完整六维。</p><label>浏览职业（英文标题或O*NET代码）<input id="career-search" placeholder="例如 Software、Designer"></label><button id="search-careers">搜索</button><div id="direction-list">${directionTiles()}</div><div class="card">${field('custom-direction','也可以自行填写一个方向，不虚构O*NET分数',handoff?.SearchIntentV2.selectedDirections.find(d=>!d.onetCodes.length)?.roleFamily??'')}<p class="muted">最多选3个方向。O*NET®为美国职业参考，国内JD映射待核查；没有自动判断真实岗位或公司。</p><button id="confirm-directions" class="primary">确认本次搜索方向</button><p>${handoff?'搜索意向已保存，可导出。':'先确认方向，再导出交接文件；也可确认暂不确定。'}</p></div><div class="card"><h3>你的可读画像</h3>${report.sections.map(section=>`<details><summary>${esc(section.title)}</summary>${section.claims.map(c=>`<p>${esc(c.text)}</p>${c.evidenceIds.length?`<small>依据：${c.evidenceIds.map(id=>{const e=report.evidence.find(e=>e.evidenceId===id);return esc(e?.text??e?.locator??id);}).join('；')}</small>`:''}`).join('')}</details>`).join('')}<button id="download-report">下载可读报告</button></div><div class="actions"><button id="download-v2" ${handoff?'':'disabled'}>下载V2 JSON</button><button id="download-intent" ${handoff?'':'disabled'}>仅下载SearchIntentV2</button><button id="download-v1" ${handoff?'':'disabled'}>兼容导出v1</button></div><p class="muted">V2包含确认经历及依据，不包含简历原文件或原题答案。v1会明确说明未传递的字段；不能表达的硬条件会拒绝降级。</p><div class="actions">${s.imported?'':'<button id="edit">修改并创建新版本</button>'}<button id="new">新建画像</button><button id="delete">删除本人的此项目</button></div>`;
 bind();if((step===1&&s.attempts['onet-mini-ip'])||(step===2&&s.attempts['mini-ipip'])){
  const id=step===1?'onet-mini-ip':'mini-ipip',sessionId=s.id;widget=mountBattery(document.getElementById('survey'),tool(id),s.attempts[id],()=>{const snapshot=widget.capture();run(async()=>{if(s.id!==sessionId||s.step!==step)return;const a=s.attempts[id];s=await api('attempts/'+a.id,'PATCH',{expectedRevision:s.revision,instrumentVersion:a.instrumentVersion,scoringVersion:a.scoringVersion,...snapshot});notice.textContent='已自动保存';});},()=>document.getElementById('next').click());
 }
}
function directionTiles(){const selected=handoff?.SearchIntentV2.selectedDirections.flatMap(d=>d.onetCodes)??[];return choices.map(c=>`<label class="tile"><input name="direction" type="checkbox" value="${c.onetCode}" ${selected.includes(c.onetCode)?'checked':''}> <strong>${esc(c.titleZh?c.titleZh+' / '+c.title:c.title)}</strong><small>${c.onetCode}${c.pearsonR===undefined||c.pearsonR===null?'':` · r=${c.pearsonR.toFixed(4)} · 并列位次 ${c.rank}`}</small><small>${esc(c.description)}</small><a href="${c.sourceUrl}" target="_blank" rel="noopener">职业参考来源</a></label>`).join('');}
async function proceed(allowIncomplete=false){clearTimeout(draftTimer);const step=s?.step??0;
 if(step===0){s=await api('sessions','POST',{battery:document.getElementById('battery').value,mode:document.getElementById('mode').value});await saveStep(s.battery==='None'?3:1);}
 else if(step===1||step===2&&s.attempts['mini-ipip']){await saveSurvey();const result=await scoreCurrent(step===1?'onet-mini-ip':'mini-ipip');if(!result.complete&&!allowIncomplete)throw new Error('请完成整套题本，或选择“暂不完成”；草稿已保存。');await saveStep(step+1);}
 else if(step===6){if(!document.getElementById('confirm').checked)throw new Error('请勾选本人确认');const x=await api('profiles/'+s.profileId+'/confirm','POST',{expectedRevision:s.revision,confirmed:true});s=x.session;profile=x.profile;await saveStep(7);await loadFinal();}
 else{if(step===4&&s.claims.some(c=>c.status==='pending'))throw new Error('请逐条确认或拒绝提取候选');await saveStep(step+1,captureDraft());}render();
}
async function pollJob(job){notice.textContent='正在本地解析，等待结果…';while(job.status==='processing'){await new Promise(r=>setTimeout(r,500));job=await api('resume-imports/'+job.id);}s=await api('sessions/'+s.id);render();notice.textContent=job.status==='completed'?`已提取${job.candidateCount}项；${job.warnings.join(' ')}`:job.error?.message??'解析失败，请手填';}
function bind(){on('next',()=>proceed());on('skip',()=>proceed(true));on('save',async()=>{await saveSurvey();notice.textContent='已保存，刷新可恢复。';});on('back',async()=>{if(widget)await saveSurvey();await saveStep(s.step===3&&s.battery==='None'?0:s.step-1,captureDraft());render();});
 on('extract-statement',async()=>{s=await api('sessions/'+s.id+'/statements','POST',{expectedRevision:s.revision,text:document.getElementById('statement').value});render();});
 on('upload',async()=>{const file=document.getElementById('resume-file').files[0];if(!file)throw new Error('先选择文件');if(file.size>10*1024*1024)throw new Error('文件超过10MB');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const x=await api('resume-imports','POST',{sessionId:s.id,expectedRevision:s.revision,filename:file.name,base64:btoa(binary)});s=x.session;await pollJob(x.job);});
 document.querySelectorAll('[data-claim]').forEach(button=>button.onclick=()=>run(async()=>{const index=Number(button.dataset.claim),c=s.claims[index];s=await api('claims/'+c.claimId,'PATCH',{expectedRevision:s.revision,status:button.dataset.status,kind:document.getElementById('kind-'+index).value,description:document.getElementById('claim-'+index).value});render();}));
 document.querySelectorAll('[data-insight]').forEach(button=>button.onclick=()=>run(async()=>{const index=Number(button.dataset.insight),c=s.insights[index];s=await api('claims/'+c.insightId,'PATCH',{expectedRevision:s.revision,status:button.dataset.status,description:document.getElementById('insight-'+index).value});render();}));
 on('search-careers',async()=>{choices=(await api('catalog?q='+encodeURIComponent(document.getElementById('career-search').value))).items;document.getElementById('direction-list').innerHTML=directionTiles();});
 on('confirm-directions',async()=>{const selectedCodes=[...document.querySelectorAll('[name=direction]:checked')].map(x=>x.value);const x=await api('search-intents','POST',{expectedRevision:s.revision,profileId:s.profileId,profileRevision:profile.revision,selectedCodes,customDirection:document.getElementById('custom-direction').value,maxCandidates:3});s=x.session;handoff=await api('profiles/'+s.profileId+'/export?revision='+profile.revision);render();notice.textContent='搜索意向已保存。';});
 on('download-v2',()=>download('xray-profile-bundle-v2.json',handoff));on('download-intent',()=>download('xray-search-intent-v2.json',handoff.SearchIntentV2));
 on('download-v1',async()=>{const x=await api('profiles/'+s.profileId+'/export?revision='+profile.revision+'&format=v1');download('xray-v1-with-compatibility-warnings.json',x);notice.textContent=x.compatibilityWarnings.join(' ');});
 on('download-report',async()=>{const x=await api('profiles/'+s.profileId+'/report?revision='+profile.revision+'&format=markdown');download('xray-a-report-v'+profile.revision+'.md',x.markdown,'text/markdown');});
 on('edit',async()=>{await saveStep(4);render();});on('new',()=>{s=null;profile=null;handoff=null;render();});
 on('delete',async()=>{if(!confirm('删除此项目的本人画像版本和私有文件？历史rubbish存档不受影响。'))return;await api('profiles/'+s.profileId,'DELETE',{});s=null;render();});
 const importer=document.getElementById('import');if(importer)importer.onchange=()=>run(async()=>{const file=importer.files[0];if(file.size>6000000)throw new Error('导入文件过大');s=await api('import','POST',JSON.parse(await file.text()));await loadFinal();render();});
}
app.addEventListener('input',event=>{if(!s||!([3,5].includes(s.step)||s.step===4&&event.target.id==='statement')||navigationPending)return;clearTimeout(draftTimer);const step=s.step,id=s.id;draftTimer=setTimeout(()=>{if(s?.id!==id||s.step!==step||navigationPending)return;const d=captureDraft();run(async()=>{if(s?.id!==id||s.step!==step)return;await saveStep(step,d);notice.textContent='已自动保存';});},350);});
await run(async()=>{bank=await api('bootstrap');s=bank.sessions.sort((a,b)=>a.updatedAt.localeCompare(b.updatedAt)).at(-1);if(s?.step===7)await loadFinal();render();});
