import test from 'node:test';
import assert from 'node:assert/strict';
import {questions,score,validateAnswers} from '../src/questionnaire.mjs';
import {Service} from '../src/service.mjs';
import {validateExport} from '../src/contracts.mjs';
import {validatePreference} from '../src/contracts.mjs';
const background={education:null,major:null,skills:[],experiences:[]};
test('known null constraints, lost hard filters and stale confirmations rejected',()=>{assert.throws(()=>validatePreference({key:'accept_sales_kpi',value:null,strength:'hard',confirmed:true}));const s=new Service();const a=s.create('u');const body={expectedRevision:1,confirmed:true,background,goals:[],preferences:[{key:'accept_sales_kpi',value:false,strength:'hard',confirmed:true}]};s.confirm('u',a.id,body);assert.throws(()=>s.confirm('u',a.id,body),e=>e.status===409);s.intent('u',{assessmentId:a.id,profileRevision:1,industryTags:[],roleTypes:[]});const x=s.export('u',a.projectId);assert.throws(()=>validateExport({...x,SearchIntent:{...x.SearchIntent,filters:[]}}));assert.equal(s.state.metadata[`${a.profileId}:1`].answersSnapshot.q01,undefined);a.version='future';assert.throws(()=>s.result('u',a.id));});
test('48 unique questions, group counts and six legal options',()=>{assert.equal(questions.length,48);assert.equal(new Set(questions.map(q=>q.id)).size,48);assert.deepEqual([...new Set(questions.map(q=>q.group))].map(g=>questions.filter(q=>q.group===g).length),[18,10,8,8,4]);questions.forEach(q=>assert.equal(q.options.length,6));});
test('readable portrait uses exactly the server score and coverage',()=>{const result=score({q01:5,q02:4,q03:3});for(const section of result.portrait.sections)for(const d of section.dimensions){assert.equal(d.score,result.scores[d.key]);assert.deepEqual(d.coverage,result.coverage[d.key]);}assert.equal(result.portrait.interpretation,result.interpretation);assert.equal(result.portrait.validation,'prototype');});
test('unknown, exact 75% boundary, reverse and deterministic score',()=>{assert.equal(score({}).scores.autonomy,null);assert.equal(score({q29:5,q30:5}).scores.autonomy,null);assert.equal(score({q29:5,q30:5,q31:5}).scores.autonomy,100);const a={q29:1,q30:1,q31:1};assert.deepEqual(score(a),score(a));assert.equal(score(a,questions.map(q=>({...q,reverse:true}))).scores.autonomy,100);assert.throws(()=>validateAnswers({q01:3.5}));assert.throws(()=>validateAnswers({fake:3}));});
test('ownership, revision conflict and bank version checked',()=>{const s=new Service();const a=s.create('u');assert.throws(()=>s.owned('v',a.id),e=>e.status===403);s.update('u',a.id,{expectedRevision:1,version:'1',answers:{q01:5}});assert.throws(()=>s.update('u',a.id,{expectedRevision:1,version:'1',answers:{}}),e=>e.status===409);assert.throws(()=>s.update('u',a.id,{expectedRevision:2,version:'2',answers:{}}));assert.equal(a.answers.q01,5);});
test('immutable revisions, unknown filters and export references',()=>{const s=new Service();const a=s.create('u');const payload={expectedRevision:1,confirmed:true,background,goals:[],preferences:[{key:'accept_sales_kpi',value:false,strength:'hard',confirmed:true},{key:'accept_travel',value:false,strength:'hard',confirmed:false}]};const p=s.confirm('u',a.id,payload);const i=s.intent('u',{assessmentId:a.id,profileRevision:p.revision,industryTags:['software_it'],roleTypes:['product_operations']});assert.deepEqual(i.industryCodes,['I']);assert.equal(i.filters[1].strength,'unknown');assert.equal(i.filters[1].value,null);assert.equal(s.confirm('u',a.id,{...payload,expectedRevision:a.revision,goals:['新目标']}).revision,2);const x=s.export('u',a.projectId);assert.equal(x.UserProfile.revision,1);assert.deepEqual(x.UserProfile.goals,[]);validateExport(x);x.UserProfile.goals.push('外部修改');assert.deepEqual(s.state.profiles[0].goals,[]);});
test('import rejects invalid references and unconfirmed hard filters',()=>{const s=new Service();const a=s.create('u');s.confirm('u',a.id,{expectedRevision:1,confirmed:true,background,goals:[],preferences:[]});s.intent('u',{assessmentId:a.id,profileRevision:1,industryTags:[],roleTypes:[]});const x=s.export('u',a.projectId);assert.throws(()=>validateExport({...x,SearchIntent:{...x.SearchIntent,profileRevision:2}}));assert.throws(()=>validateExport({...x,SearchIntent:{...x.SearchIntent,filters:[{key:'accept_sales_kpi',value:false,strength:'hard'}]}}));const imported=s.import('v',x);assert.notEqual(imported.attempt.projectId,a.projectId);validateExport(s.export('v',imported.attempt.projectId));});

