"use client";
import {use,useEffect,useState} from "react";
import {PageHeader} from "@/packages/ui";
type Job={title:string;rawJd:string;city:string|null;sourceUrl:string|null;publishedAt:string|null};
type Context={companyName:string|null;profileRevision:number;previousRetrievedAt:string;job:Job};
export default function MaterialsPage({params}:{params:Promise<{id:string}>}){
 const {id}=use(params),[context,setContext]=useState<Context|null>(null),[job,setJob]=useState<Job>({title:"",rawJd:"",city:null,sourceUrl:null,publishedAt:null}),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<{reportUrl:string;warnings:string[]}|null>(null);
 useEffect(()=>{void(async()=>{try{const r=await fetch("/api/integration/reports/"+id+"/materials",{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error?.message??"读取失败");setContext(d);setJob(d.job);}catch(e){setError(e instanceof Error?e.message:"读取失败");}})();},[id]);
 async function save(e:React.FormEvent){e.preventDefault();if(!confirmed)return;setBusy(true);setError("");setResult(null);try{const r=await fetch("/api/integration/reports/"+id+"/materials",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...job,sameJobConfirmed:confirmed})}),d=await r.json();if(!r.ok)throw Error(d.error?.message??"保存失败");setResult(d);}catch(e){setError(e instanceof Error?e.message:"保存失败");}finally{setBusy(false);}}
 return <main><PageHeader title="更新这份岗位的材料"><p>岗位描述或来源有变化时，保留原报告并用新JD另存一份分析。</p></PageHeader>{context&&<section className="panel"><p>公司名称线索：{context.companyName??"未提供"}。沿用需求版本 {context.profileRevision}；不代表已确认现实企业身份。</p><p>上次材料录入：{context.previousRetrievedAt}。录入时间不证明招聘信息仍有效。</p><p>本次按新JD重建岗位材料。旧薪资及在招声明不自动沿用，未重新提供的字段保持未知；历史核验回复保留待核验状态。</p><form onSubmit={save} onChange={()=>setResult(null)}><fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}><label>岗位名称<input value={job.title} onChange={e=>setJob({...job,title:e.target.value})} maxLength={500} required/></label><label>新的JD原文<textarea value={job.rawJd} onChange={e=>setJob({...job,rawJd:e.target.value})} maxLength={50000} required rows={10}/></label><label>工作城市（选填）<input value={job.city??""} onChange={e=>setJob({...job,city:e.target.value})} maxLength={500}/></label><label>来源链接（选填）<input type="url" value={job.sourceUrl??""} onChange={e=>setJob({...job,sourceUrl:e.target.value})} maxLength={2048}/></label><label>来源发布日期（选填，含时区的ISO日期时间）<input value={job.publishedAt??""} onChange={e=>setJob({...job,publishedAt:e.target.value})} placeholder="例如 2026-10-03T09:00:00+08:00"/></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>这是同一份岗位的新材料；如果公司或实际岗位变了，应另建候选。</label><button disabled={busy||!confirmed}>{busy?"生成中…":"保存新材料并生成报告"}</button></fieldset></form></section>}{error&&<p role="alert">{error}</p>}{result&&<section className="panel"><h2>新材料报告已保存</h2>{result.warnings.map(w=><p key={w}>{w}</p>)}<a href={result.reportUrl}>查看新报告与材料变化 →</a></section>}<p><a href={"/flow/reports/"+id}>回到更新前报告</a> · <a href="/research">调查其他公司与岗位</a></p></main>;
}
