"use client";
import {useEffect,useState} from "react";
import {PageHeader} from "@/packages/ui";
import {latestCandidates,comparisonGroups,type HistoryItem} from "@/packages/integration/report-selection";
export default function ComparePage(){
 const [items,setItems]=useState<HistoryItem[]>([]),[group,setGroup]=useState(""),[ids,setIds]=useState<string[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[result,setResult]=useState<{reportUrl:string;warnings:string[]}|null>(null);
 useEffect(()=>{(async()=>{const boot=await fetch("/api/a/needs/bootstrap",{cache:"no-store"});if(!boot.ok)throw Error("本地会话恢复失败");const response=await fetch("/api/integration/history",{cache:"no-store"}),data=await response.json();if(!response.ok)throw Error(data.error?.message??"读取失败");setItems(data.reports);const groups=comparisonGroups(data.reports);setGroup(groups.find(g=>g.mode==="manual")?.id??groups[0]?.id??"");})().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 const groups=comparisonGroups(items),candidates=latestCandidates(items,group);
 function toggle(item:HistoryItem){setError("");setResult(null);if(ids.includes(item.reportId)){setIds(ids.filter(id=>id!==item.reportId));return;}if(ids.length===3){setError("最多比较三个岗位");return;}setIds([...ids,item.reportId]);}
 async function compare(){setBusy(true);setError("");setResult(null);try{const response=await fetch("/api/integration/compare",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reportIds:ids})}),data=await response.json();if(!response.ok)throw Error(data.error?.message??"比较失败");setResult(data);}catch(e){setError(e instanceof Error?e.message:"比较失败");}finally{setBusy(false);}}
 return <main><PageHeader title="比较正在考虑的岗位"><p>选择同一需求版本的两至三份岗位，逐项比较。未知保持未知，不选冠军。</p></PageHeader><p><a href="/analyze">用同一需求记录分析另一份 JD →</a> · <a href="/history">我的报告与旧版本</a></p>{loading&&<p role="status">正在读取报告…</p>}{!loading&&!groups.length&&<p>还没有单岗位报告。先分析一份 JD，再复用同一需求记录分析另一份。</p>}{groups.length>0&&<section className="panel"><label>用于比较的需求版本<select value={group} disabled={busy} onChange={e=>{setGroup(e.target.value);setIds([]);setResult(null);setError("");}}>{groups.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label><p>仅显示此版本每份岗位最近生成的报告，避免把需求修订、核验回复或JD更新当成多个候选。生成时间不代表资料已核验或招聘仍有效。</p><p>本组有 {candidates.length} 个不同岗位，已选 {ids.length} 个。旧版本可从“我的报告”打开。</p>{candidates.length<2&&<p>还需要另一个岗位。复用该需求版本分析第二份JD，或将已有岗位按同一新需求版本重新分析。</p>}</section>}{candidates.map(item=><section className="panel" key={item.reportId}><label><input type="checkbox" checked={ids.includes(item.reportId)} disabled={busy} onChange={()=>toggle(item)}/>{item.jobTitles[0]}</label><p>{item.kindLabel} · 需求版本 {item.profileRevision} · 生成于 {new Date(item.generatedAt).toLocaleString("zh-CN")}</p><a href={item.reportUrl}>查看此报告</a> · <a href={"/revise/"+item.reportId}>修改需求后重新分析</a></section>)}<button disabled={ids.length<2||busy} onClick={compare}>{busy?"正在生成比较报告…":"比较所选岗位"}</button>{error&&<p role="alert">{error}</p>}{result&&<section className="panel"><h2>比较报告已生成</h2>{result.warnings.map(w=><p key={w}>{w}</p>)}<a href={result.reportUrl}>查看逐项比较 →</a></section>}</main>;
}
