import {createSelectedNeeds} from './test-needs-fixture';
import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createAHost } from "./a-host";
import { createDemoFlow } from "./demo-flow";

test("A choices reach B/C; revisions, seven topics and exports stay bound to their owner", async () => {
  const dir = mkdtempSync(join(tmpdir(), "xray-integration-"));
  let a = createAHost(dir);
  const boot = await a.handle(new Request("http://127.0.0.1/api/a/needs/bootstrap"));
  const cookie = boot.headers.get("set-cookie")!.split(";")[0];
  const owner = a.owner(new Request("http://127.0.0.1/api/integration/demo", { headers: { cookie } }));
  let session = createSelectedNeeds(a.service,owner, { mode: "demo" });
  const data = structuredClone(session.data);
  data.conditions.find((x: any) => x.key === "city").value = ["上海"];
  data.conditions.find((x: any) => x.key === "city").strength = "hard";
  data.conditions.find((x: any) => x.key === "accept_sales_kpi").value = false;
  data.conditions.find((x: any) => x.key === "accept_sales_kpi").strength = "hard";
  session = a.service.update(owner, session.id, { expectedRevision: session.revision, questionnaireVersion: session.questionnaireVersion, step: 8, data });
  const first = a.service.confirm(owner, session.id, { expectedRevision: session.revision, confirmed: true });
  const flow = createDemoFlow();
  const result = await flow.run(owner, first.export);
  assert.equal(result.jobCount, 1);
  const frozen = await (await flow.read(owner, result.reportId, "handoff")).json();
  assert.equal(frozen.report.results[0].recommendation, "deprioritize");
  assert.equal(frozen.aExport.checksum, first.export.checksum);
  assert.equal(frozen.aExport.JobNeedsSnapshot.topics.length, 7);
  assert.equal(frozen.bundle.projectId, first.export.UserProfile.projectId);
  assert.equal((await flow.read("other-owner", result.reportId)).status, 404);
  assert.match(await (await flow.read(owner, result.reportId, "md")).text(), /销售|签单/);
  assert.match(await (await flow.read(owner, result.reportId)).text(), /产品运营/);
  a = createAHost(dir);
  assert.deepEqual(a.service.export(owner, session.id, 1), first.export);
  const d = structuredClone(first.session.data);
  d.conditions.find((x: any) => x.key === "accept_sales_kpi").value = true;
  session = a.service.update(owner, session.id, { expectedRevision: first.session.revision, questionnaireVersion: session.questionnaireVersion, step: 8, data: d });
  const second = a.service.confirm(owner, session.id, { expectedRevision: session.revision, confirmed: true });
  const result2 = await flow.run(owner, second.export);
  const revised = await (await flow.read(owner, result2.reportId, "handoff")).json();
  assert.equal(revised.report.profileRevision, 2);
  assert.equal(revised.report.results[0].dimensions.find((d:any)=>d.key==="personal_fit").status,"unknown");
  assert.ok(revised.report.results[0].constraints.some((c:any)=>c.result==="pass"));
  assert.ok(revised.report.results[0].constraints.some((c:any)=>c.result==="unknown"));
  const revisedMd=await(await flow.read(owner,result2.reportId,"md")).text();
  assert.equal(revised.actions[0].recommendation,"verify_first");
  assert.match(revisedMd,/建议动作：\*\*verify_first\*\*/);
  assert.doesNotMatch(revisedMd,/建议动作：\*\*explore\*\*/);
  assert.match(revisedMd,/实际工作地点/);
  assert.notEqual(revised.report.results[0].recommendation, "deprioritize");
  assert.deepEqual(await (await flow.read(owner, result.reportId, "handoff")).json(), frozen);
  const manual = createSelectedNeeds(a.service,owner, { mode: "manual" });
  const confirmedManual = a.service.confirm(owner, manual.id, { expectedRevision: manual.revision, confirmed: true });
  await assert.rejects(flow.run(owner, confirmedManual.export), /真实需求不会转换/);
  const empty = structuredClone(second.export);
  empty.SearchIntent.cities = ["杭州"];
  empty.UserProfile.preferences.find((x: any) => x.key === "city").value = ["杭州"];
  empty.SearchIntent.filters.find((x: any) => x.key === "city").value = ["杭州"];
  const noCandidate = await flow.run(owner, empty);
  const snapshot = await (await flow.read(owner, noCandidate.reportId, "handoff")).json();
  assert.equal(noCandidate.jobCount, 0);
  assert.equal(snapshot.report.results.length, 0);
});

test("mounted A API rejects cross-site, missing ownership, invalid JSON and stale writes", async () => {
  const a = createAHost(mkdtempSync(join(tmpdir(), "xray-a-host-")));
  assert.equal((await a.handle(new Request("http://127.0.0.1/api/a/needs/sessions/no-record"))).status, 401);
  assert.equal((await a.handle(new Request("http://127.0.0.1/api/a/needs/bootstrap", { headers: { origin: "https://example.com" } }))).status, 403);
  const boot = await a.handle(new Request("http://127.0.0.1/api/a/needs/bootstrap"));
  const cookie = boot.headers.get("set-cookie")!.split(";")[0];
  const post = (body: string) => a.handle(new Request("http://127.0.0.1/api/a/needs/sessions", { method: "POST", headers: { cookie }, body }));
  assert.equal((await post("invalid")).status, 422);
  const session = await (await post('{"mode":"demo"}')).json();
  const result = await a.handle(new Request(`http://127.0.0.1/api/a/needs/sessions/${session.id}`, { method: "PATCH", headers: { cookie }, body: JSON.stringify({ expectedRevision: 999, questionnaireVersion: session.questionnaireVersion, step: 8, data: session.data }) }));
  assert.equal(result.status, 409);
});

test("direct manual JD analysis preserves a selected job despite search city conflict", async () => {
  const a = createAHost(mkdtempSync(join(tmpdir(), "xray-manual-")));
  const owner = "manual-test-owner";
  let session = createSelectedNeeds(a.service,owner, { mode: "manual" });
  const data = structuredClone(session.data);
  data.conditions.find((x: any) => x.key === "city").value = ["上海"];
  data.conditions.find((x: any) => x.key === "city").strength = "hard";
  session = a.service.update(owner, session.id, { expectedRevision: session.revision, questionnaireVersion: session.questionnaireVersion, step: 8, data });
  const confirmed = a.service.confirm(owner, session.id, { expectedRevision: session.revision, confirmed: true });
  const flow = createDemoFlow();
  const result = await flow.runManual(owner, confirmed.export, { title: "用户自己的岗位", rawJd: "工作地点杭州，负责团队协作。", city: "杭州", companyName: "用户录入公司" });
  const handoff = await (await flow.read(owner, result.reportId, "handoff")).json();
  assert.equal(result.jobCount, 1);
  assert.equal(handoff.bundle.mode, "manual");
  assert.equal(handoff.bundle.jobs[0].city, "杭州");
  assert.equal(handoff.bundle.companies[0].identityStatus, "unresolved");
  assert.equal(handoff.bundle.evidence[0].verification, "unverified");
  assert.equal(handoff.report.results[0].recommendation, "verify_first");
  assert.equal((await flow.read("other-owner", result.reportId)).status, 404);
  const html = await (await flow.read(owner, result.reportId)).text();
  assert.match(html, /用户提供资料.*未独立核验/);
  assert.doesNotMatch(html, /公司和岗位均为合成样例/);
  await assert.rejects(flow.runManual(owner, { ...confirmed.export, UserProfile: { ...confirmed.export.UserProfile, mode: "demo" } }, { title: "无效", rawJd: "无效" }), /人工需求版本/);
});
