import test from "node:test";
import assert from "node:assert/strict";
import {mkdtempSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createAHost} from "./a-host";
import {createDemoFlow} from "./demo-flow";
test("material updates keep job lineage and old snapshots while rebuilding only the new unverified JD",async()=>{
 const dir=mkdtempSync(join(tmpdir(),"xray-material-")),owner="material-owner",a=createAHost(join(dir,"a")),initial=a.service.create(owner,{mode:"manual"});
 const data=structuredClone(initial.data);data.conditions.find((c:any)=>c.key==="accept_sales_kpi").value=false;data.conditions.find((c:any)=>c.key==="accept_sales_kpi").strength="hard";
 const session=a.service.update(owner,initial.id,{expectedRevision:initial.revision,questionnaireVersion:initial.questionnaireVersion,step:8,data}),input=a.service.confirm(owner,session.id,{expectedRevision:session.revision,confirmed:true}).export;
 let flow=createDemoFlow({dataDir:join(dir,"reports")});const first=await flow.runManual(owner,input,{title:"人工岗位原版",companyName:"原主体线索",rawJd:"人工测试。销售KPI：有。",sourceUrl:"https://example.com/old"}),old=await (await flow.read(owner,first.reportId,"handoff")).json(),oldMd=await (await flow.read(owner,first.reportId,"md")).text();
 const question=flow.feedbackContext(owner,first.reportId).questions[0],noted=await flow.addFeedback(owner,first.reportId,{questionId:question.id,answer:"旧材料的口头回复，未核验"});
 flow=createDemoFlow({dataDir:join(dir,"reports")});const context=flow.materialContext(owner,noted.reportId);
 assert.equal(context.job.rawJd,old.bundle.jobs[0].rawJd);
 await assert.rejects(flow.updateMaterial(owner,noted.reportId,{...context.job,rawJd:"新资料"}),/true/);
 await assert.rejects(flow.updateMaterial("other-owner",noted.reportId,{title:"x",rawJd:"y"}),/本会话无/);
 await assert.rejects(flow.updateMaterial(owner,noted.reportId,{...context.job,companyName:"其他主体"}));
 await assert.rejects(flow.updateMaterial(owner,noted.reportId,{...context.job,sourceUrl:"javascript:alert(1)"}));
 await assert.rejects(flow.updateMaterial(owner,noted.reportId,{...context.job,sameJobConfirmed:true}),/材料没有变化/);
 const updated=await flow.updateMaterial(owner,noted.reportId,{sameJobConfirmed:true,title:"人工岗位修订版",rawJd:"更新人工测试。销售KPI：无。培训情况未知。",sourceUrl:"https://example.com/new"}),next=await (await flow.read(owner,updated.reportId,"handoff")).json();
 assert.equal(next.bundle.jobs[0].jobId,old.bundle.jobs[0].jobId);assert.equal(next.bundle.jobs[0].companyId,old.bundle.jobs[0].companyId);assert.equal(next.report.profileRevision,old.report.profileRevision);assert.equal(old.report.results[0].recommendation,"deprioritize");assert.equal(next.report.results[0].recommendation,"verify_first");assert.deepEqual(next.aExport,old.aExport);assert.notEqual(next.bundle.retrievedAt,old.bundle.retrievedAt);
 assert.equal(next.bundle.evidence.length,1);assert.equal(next.bundle.evidence[0].verification,"unverified");assert.equal(next.bundle.evidence[0].url,"https://example.com/new");assert.notEqual(next.bundle.evidence[0].evidenceId,old.bundle.evidence[0].evidenceId);
 assert.equal(next.bundle.facts.find((f:any)=>f.key==="job.sales_kpi").value,false);assert.equal(old.bundle.facts.find((f:any)=>f.key==="job.sales_kpi").value,true);assert.equal(next.bundle.companies[0].identityStatus,"unresolved");assert.equal(next.verificationNotes[0].verification,"user_provided_unverified");assert.equal(next.materialChanges.previousReportId,noted.reportId);assert.equal(next.materialChanges.beforeRecommendation,"deprioritize");assert.equal(next.materialChanges.afterRecommendation,"verify_first");
 const md=await (await flow.read(owner,updated.reportId,"md")).text(),html=await (await flow.read(owner,updated.reportId)).text();assert.match(md,/岗位材料已更新/);assert.match(html,/旧核验回复作为历史记录/);assert.equal(await (await flow.read(owner,first.reportId,"md")).text(),oldMd);
 await assert.rejects(flow.compare(owner,[first.reportId,updated.reportId]),/重复|同一|岗位/);
 const followQuestion=flow.feedbackContext(owner,updated.reportId).questions[0],follow=await flow.addFeedback(owner,updated.reportId,{questionId:followQuestion.id,answer:"对新材料的补充口头回复"}),followData=await (await flow.read(owner,follow.reportId,"handoff")).json();assert.deepEqual(followData.materialChanges,next.materialChanges);assert.equal(followData.verificationNotes.length,2);
 const restored=createDemoFlow({dataDir:join(dir,"reports")});assert.equal(await (await restored.read(owner,updated.reportId,"md")).text(),md);assert.equal(restored.materialContext(owner,updated.reportId).job.title,"人工岗位修订版");
 const second=await flow.runManual(owner,input,{title:"另一岗位",rawJd:"测试第二岗位"}),compared=await flow.compare(owner,[updated.reportId,second.reportId]);assert.throws(()=>flow.materialContext(owner,compared.reportId),/一份人工JD/);
});
