import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { ReportArchive } from "./report-archive";
import { createAHost } from "./a-host";
import { createDemoFlow } from "./demo-flow";
test("reports survive service restart with immutable needs, all exports and owner isolation",async()=>{
 const dir=mkdtempSync(join(tmpdir(),"xray-archive-")), a=createAHost(join(dir,"a")), owner="owner-a";
 const session=a.service.create(owner,{mode:"manual"});
 const confirmed=a.service.confirm(owner,session.id,{expectedRevision:session.revision,confirmed:true});
 let flow=createDemoFlow({dataDir:join(dir,"reports")});
 const r=await flow.runManual(owner,confirmed.export,{title:"归档岗位",rawJd:"实际岗位待核验"});
 const before=await(await flow.read(owner,r.reportId,"handoff")).json();
 const md=await(await flow.read(owner,r.reportId,"md")).text();
 flow=createDemoFlow({dataDir:join(dir,"reports")});
 assert.deepEqual(await(await flow.read(owner,r.reportId,"handoff")).json(),before);
 assert.equal(await(await flow.read(owner,r.reportId,"md")).text(),md);
 assert.match(await(await flow.read(owner,r.reportId)).text(),/你关心的事项与下一步/);
 assert.ok((await(await flow.read(owner,r.reportId,"json")).json()).productNeeds);
 assert.equal(flow.list(owner).length,1);assert.equal(flow.list("other-owner").length,0);
 assert.equal((await flow.read("other-owner",r.reportId)).status,404);
 assert.equal((await flow.read(owner,"../../outside")).status,404);
 const archive=new ReportArchive(join(dir,"reports"));
 assert.throws(()=>archive.save(archive.read(owner,r.reportId)!),/不可覆盖/);
 const next=await flow.runManual(owner,confirmed.export,{title:"第二个岗位",rawJd:"第二份岗位材料"});
 assert.notEqual(next.reportId,r.reportId);assert.equal(flow.list(owner).length,2);
 assert.deepEqual(await(await flow.read(owner,r.reportId,"handoff")).json(),before);
 const folder=join(dir,"reports",readdirSync(join(dir,"reports"))[0]), file=join(folder,r.reportId+".json");
 const wrapped=JSON.parse(readFileSync(file,"utf8"));wrapped.payload += " ";writeFileSync(file,JSON.stringify(wrapped));
 await assert.rejects(flow.read(owner,r.reportId),/损坏/);
 assert.equal((await flow.read("other-owner",r.reportId)).status,404);
});
