import {createSelectedNeeds} from './test-needs-fixture';
import test from "node:test";
import assert from "node:assert/strict";
import {mkdtempSync} from "node:fs";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {createAHost} from "./a-host";
import {createDemoFlow} from "./demo-flow";
test("new confirmed needs re-evaluate the original evidence after restart, explain changes and preserve old reports",async()=>{
 const dir=mkdtempSync(join(tmpdir(),"xray-revisions-")),a=createAHost(join(dir,"a")),owner="version-owner";
 let s=createSelectedNeeds(a.service,owner,{mode:"demo"}),d=structuredClone(s.data);
 d.conditions.find((c:any)=>c.key==="accept_sales_kpi").value=false;d.conditions.find((c:any)=>c.key==="accept_sales_kpi").strength="hard";
 d.answers["growth.priority"]="priority";d.answers["growth.details"]=["learning"];d.answers["growth.policy"]="verify_first";
 s=a.service.update(owner,s.id,{expectedRevision:s.revision,questionnaireVersion:s.questionnaireVersion,step:8,data:d});
 const first=a.service.confirm(owner,s.id,{expectedRevision:s.revision,confirmed:true});
 let flow=createDemoFlow({dataDir:join(dir,"reports")});const r=await flow.run(owner,first.export);
 const old=await(await flow.read(owner,r.reportId,"handoff")).json();
 assert.equal(old.report.results[0].recommendation,"deprioritize");
 d=structuredClone(first.session.data);d.conditions.find((c:any)=>c.key==="accept_sales_kpi").value=true;d.answers["growth.policy"]="continue_with_unknown";
 s=a.service.update(owner,s.id,{expectedRevision:first.session.revision,questionnaireVersion:s.questionnaireVersion,step:8,data:d});
 const second=a.service.confirm(owner,s.id,{expectedRevision:s.revision,confirmed:true});
 flow=createDemoFlow({dataDir:join(dir,"reports")});
 const next=await flow.reanalyze(owner,r.reportId,second.export), revised=await(await flow.read(owner,next.reportId,"handoff")).json();
 assert.notEqual(next.reportId,r.reportId);assert.equal(revised.report.profileRevision,2);
 assert.notEqual(revised.report.results[0].recommendation,"deprioritize");
 assert.deepEqual(revised.bundle.jobs,old.bundle.jobs);assert.deepEqual(revised.bundle.facts,old.bundle.facts);assert.deepEqual(revised.bundle.evidence,old.bundle.evidence);assert.equal(revised.bundle.retrievedAt,old.bundle.retrievedAt);
 assert.equal(revised.changes.productActions[0].before,old.actions[0].recommendation);assert.equal(revised.changes.productActions[0].after,revised.actions[0].recommendation);
 assert.match(await(await flow.read(owner,next.reportId,"md")).text(),/决定前先核实.*允许带着未知继续了解/);
 assert.match(await(await flow.read(owner,next.reportId)).text(),/最终下一步/);
 assert.equal(revised.changes.previousReportId,r.reportId);assert.equal(revised.changes.conditions[0].key,"accept_sales_kpi");assert.equal(revised.changes.topics[0].topicId,"growth");
 assert.equal(revised.needsResponse.candidates[0].actionGate,"no_additional_gate");
 assert.deepEqual(await(await flow.read(owner,r.reportId,"handoff")).json(),old);
 assert.match(await(await flow.read(owner,next.reportId)).text(),/与上份报告相比/);
 await assert.rejects(flow.reanalyze("other-owner",r.reportId,second.export),/无该报告/);
 await assert.rejects(flow.reanalyze(owner,next.reportId,first.export),/更新确认版本/);
 const another=createSelectedNeeds(a.service,owner,{mode:"demo"});const other=a.service.confirm(owner,another.id,{expectedRevision:another.revision,confirmed:true});
 await assert.rejects(flow.reanalyze(owner,r.reportId,other.export),/更新确认版本/);
});
