import {createSelectedNeeds,requiredNeedsData} from './test-needs-fixture';
import {GET as materialGet,POST as materialPost} from "../../app/api/integration/reports/[id]/materials/route";
import test from "node:test";
import assert from "node:assert/strict";
import {mkdtempSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createAHost} from "./a-host";
import {createDemoFlow} from "./demo-flow";
import {POST as manualPost} from "../../app/api/integration/manual/route";
import {POST as comparePost} from "../../app/api/integration/compare/route";
import {GET as revisionGet,POST as revisionPost} from "../../app/api/integration/reports/[id]/revisions/route";
test("mounted product routes enforce owner/origin/JSON boundaries before mutating local records",async()=>{
 const dir=mkdtempSync(join(tmpdir(),"xray-routes-")),a=createAHost(join(dir,"a")),flow=createDemoFlow({dataDir:join(dir,"reports")}),globals=globalThis as any;
 const oldA=globals.__xrayAHost,oldFlow=globals.__xrayDemoFlow;globals.__xrayAHost=a;globals.__xrayDemoFlow=flow;
 try{
 const boot=await a.handle(new Request("http://127.0.0.1/api/a/needs/bootstrap")),cookie=boot.headers.get("set-cookie")!.split(";")[0],owner=a.owner(new Request("http://127.0.0.1",{headers:{cookie}}));
 const post=(path:string,body:unknown,headers:Record<string,string>={cookie})=>new Request("http://127.0.0.1"+path,{method:"POST",headers:{"content-type":"application/json",...headers},body:typeof body==="string"?body:JSON.stringify(body)});
 const manual=(b:unknown,h?:Record<string,string>)=>manualPost(post("/api/integration/manual",b,h));
 const job={title:"路由测试甲",rawJd:"人工路由验证岗位甲"};
 assert.equal((await manual({job,confirmUnknownNeeds:true},{origin:"https://other.example",cookie})).status,403);
 assert.equal((await manual({job,confirmUnknownNeeds:true},{})).status,401);
 assert.equal((await manual("{broken")).status,422);assert.equal((await manual({job})).status,422);
 assert.equal(a.service.bootstrap(owner).sessions.length,0);
 assert.equal((await manual({job:{title:"",rawJd:""},confirmUnknownNeeds:true})).status,422);assert.equal(a.service.bootstrap(owner).sessions.length,0);
 const session=createSelectedNeeds(a.service,owner,{mode:"manual"}),confirmed=a.service.confirm(owner,session.id,{expectedRevision:session.revision,confirmed:true});
 const r1=await manual({job,sessionId:session.id,revision:1});assert.equal(r1.status,200);const first=await r1.json();assert.deepEqual(first.needsSession,{sessionId:session.id,revision:1});const context={params:Promise.resolve({id:first.reportId})};
 const r2=await manual({job:{title:"路由测试乙",rawJd:"人工路由验证岗位乙"},sessionId:session.id,revision:1});assert.equal(r2.status,200);const second=await r2.json();
 const get=(path:string,c=cookie)=>new Request("http://127.0.0.1"+path,{headers:{cookie:c}});
 const boot2=await a.handle(new Request("http://127.0.0.1/api/a/needs/bootstrap")),otherCookie=boot2.headers.get("set-cookie")!.split(";")[0];
 assert.equal((await revisionGet(get("/api/integration/reports/id/revisions",otherCookie),context)).status,404);
 assert.equal((await revisionPost(post("/api/integration/reports/id/revisions",{sessionId:session.id,revision:1}),context)).status,409);
 const cmp=await comparePost(post("/api/integration/compare",{reportIds:[first.reportId,second.reportId]}));assert.equal(cmp.status,200);
 assert.equal((await comparePost(post("/api/integration/compare",{reportIds:[first.reportId,second.reportId]},{cookie:otherCookie}))).status,404);
 assert.equal((await comparePost(post("/api/integration/compare",{reportIds:[first.reportId,first.reportId]}))).status,409);
 assert.equal(flow.list(owner).length,3);
 assert.equal((await materialGet(get("/api/integration/reports/id/materials",otherCookie),context)).status,404);
 assert.equal((await materialPost(post("/api/integration/reports/id/materials",{title:"新JD",rawJd:"新资料"},{cookie,origin:"https://other.example"}),context)).status,403);
 assert.equal((await materialPost(post("/api/integration/reports/id/materials",{title:"",rawJd:""}),context)).status,422);
 assert.equal((await materialPost(post("/api/integration/reports/id/materials",{...job,companyName:"伪造主体"}),context)).status,422);
 assert.equal(flow.list(owner).length,3);
 assert.equal((await materialPost(post("/api/integration/reports/id/materials",{...job,sameJobConfirmed:true}),context)).status,409);
 assert.equal((await materialPost(post("/api/integration/reports/id/materials",{sameJobConfirmed:true,title:"路由测试甲",rawJd:"新人工路由验证岗位甲：销售KPI：无。"}),context)).status,200);
 const reportsBeforeUnknown=flow.list(owner).length;
 const unknownResponse=await manual({job:{title:"暂未填写需求的甲",rawJd:"本地测试甲"},confirmUnknownNeeds:true});
 assert.equal(unknownResponse.status,422);assert.match((await unknownResponse.json()).error.message,/请选择本次主要寻找的工作机会/);
 assert.equal(flow.list(owner).length,reportsBeforeUnknown);
 const drafts=a.service.bootstrap(owner).sessions;assert.equal(drafts.length,2);
 const unconfirmed=drafts.find((draft:any)=>draft.id!==session.id)!;assert.deepEqual(unconfirmed.confirmedRevisions,[]);
 const incomplete=a.service.get(owner,unconfirmed.id);assert.deepEqual(incomplete.data.goalIds,[]);assert.deepEqual(incomplete.data.industryTags,[]);assert.deepEqual(incomplete.data.roleTypes,[]);
 const filled=a.service.update(owner,incomplete.id,{expectedRevision:incomplete.revision,questionnaireVersion:incomplete.questionnaireVersion,step:8,data:requiredNeedsData(incomplete.data)});
 const selected=a.service.confirm(owner,filled.id,{expectedRevision:filled.revision,confirmed:true});
 const firstSelected=await manual({job:{title:"已确认需求的甲",rawJd:"本地测试甲"},sessionId:filled.id,revision:selected.export.UserProfile.revision});assert.equal(firstSelected.status,200);const selectedReport=await firstSelected.json();
 const reusedResponse=await manual({job:{title:"已确认需求的乙",rawJd:"本地测试乙"},...selectedReport.needsSession});assert.equal(reusedResponse.status,200);const reused=await reusedResponse.json();assert.deepEqual(reused.needsSession,selectedReport.needsSession);assert.equal(a.service.bootstrap(owner).sessions.length,2);
 assert.equal((await comparePost(post("/api/integration/compare",{reportIds:[selectedReport.reportId,reused.reportId]}))).status,200);
 }finally{globals.__xrayAHost=oldA;globals.__xrayDemoFlow=oldFlow;}
});
