/** Availability means an implemented generic path, never that a named platform was successfully crawled. */
export type Source={id:string;label:string;domains:string[];categories:string[];mode:'http'|'browser'|'api'|'file'|'ocr'|'client'|'event';status:'available'|'connector_pending';fields:string[];prerequisite:string;cost:'local'|'network'|'provider_unknown';implementation:'local_database'|'public_http'|'controlled_import'|'local_document_parser'|'local_ocr'|'deferred_connector';validation:'real_material_flow'|'controlled_parser_tests'|'controlled_metadata_tests'|'not_platform_verified'|'routing_only';boundary:string};
const make=(id:string,label:string,domains:string[],categories:string[],mode:Source['mode'],fields:string[],prerequisite='',available=false):Source=>({id,label,domains,categories,mode,fields,prerequisite,status:available?'available':'connector_pending',cost:mode==='file'||mode==='ocr'?'local':mode==='api'?'provider_unknown':'network',
 implementation:!available?'deferred_connector':id==='local'?'local_database':mode==='ocr'?'local_ocr':['docx','xlsx','csv'].includes(id)?'local_document_parser':mode==='file'?'controlled_import':'public_http',
 validation:!available?'routing_only':['local','public','pdf','user','official','disclosure'].includes(id)?'real_material_flow':id==='group_import'?'controlled_metadata_tests':mode==='file'||mode==='ocr'?'controlled_parser_tests':'not_platform_verified',
 boundary:!available?'专用采集按本轮安排延期；目录存在不代表已取得材料。':mode==='http'?'仅复用有界公共 HTTP；不是平台专用爬虫，每次访问及正文都须验证。':mode==='ocr'?'本机 CPU OCR；需安装固定依赖与本地模型，识别结果全部待复核；未验证真实截图总体准确率。':id==='local'?'只读候选与线索，不修改原库，不据库中公司信息认证目标岗位。':id==='group_import'?'仅主动导入、经过明确元数据门槛的本机处理；不自动读取群，不推断水军或内容真假。':'本机受控导入；原文和定位保留，用户提供不等于认证真实。'});
export const sources:Source[]=[
 make('local','只读企业候选库',[],['identity','business','finance','recruitment','employment','experience','opinion'],'file',['excerpt','job','subject'],'本机库已配置',true),
 make('public','可访问公开网页',[],['identity','business','finance','recruitment','employment','experience','opinion'],'http',['full_text','period','quote'],'正文实际可访问；逐次验证',true),
 make('pdf','PDF 文本层/有界本地扫描 OCR',[],['identity','business','finance','recruitment','employment','experience'],'file',['full_text','physical_page','bbox','quote'],'文本层复用原解析；扫描 OCR 需本机依赖，最多12页且有时限；网络取得另记状态',true),
 make('user','主动提供文字/PDF/办公文件/截图',[],['identity','business','finance','recruitment','employment','experience','opinion'],'file',['full_text','quote','table','cell','bbox'],'本机文件入口，格式与依赖逐次验证；提供者声明来源不认证真实性',true),
 make('gsxt','国家企业信用信息公示系统',['gsxt.gov.cn'],['identity'],'api',['legalName','creditCode','relation'],'授权接口或可访问材料'),
 ...[['tianyancha','天眼查','tianyancha.com'],['qixin','启信宝','qixin.com'],['qcc','企查查','qcc.com']].map(([id,label,domain])=>make(id,label,[domain],['identity','business','finance','employment'],'api',['legalName','creditCode','relation','period'],'各自授权与字段契约，不能互换接口')),
 make('aiqicha','爱企查',['aiqicha.baidu.com'],['identity','business'],'browser',['legalName','relation'],'浏览器来源适配器待接'),
 make('disclosure','巨潮/交易所披露',['cninfo.com.cn','szse.cn','sse.com.cn'],['business','finance','employment'],'http',['period','value','unit','reportingScope'],'复用公开正文/PDF获取，专用发现待接',true),
 make('official','公司官网/招聘官网/官方公众号',[],['identity','business','recruitment','employment','experience'],'http',['full_text','role','period'],'用户指定公共URL或搜索发现；可见公众号正文',true),
 make('news','36氪/虎嗅/财新/界面',['36kr.com','huxiu.com','caixin.com','jiemian.com'],['business','opinion'],'http',['full_text','origin','period'],'复用公开HTTP；付费/限制页面保留访问状态',true),
 make('procurement','招投标/政府采购/监管公示',['ccgp.gov.cn'],['business','employment'],'http',['subject','period','eventStage'],'公开正文可访问',true),
 ...[['boss','BOSS直聘','zhipin.com'],['liepin','猎聘','liepin.com'],['zhaopin','智联','zhaopin.com'],['51job','前程无忧','51job.com'],['lagou','拉勾','lagou.com'],['shixiseng','实习僧','shixiseng.com'],['yingjiesheng','应届生','yingjiesheng.com']].map(([id,label,domain])=>make(id,label,[domain],['recruitment'],'browser',['role','city','salary','period'],'岗位来源适配器待接；不凭搜索摘要判定在招')),
 make('campus','公司招聘/校园就业网',[],['recruitment'],'http',['role','city','period'],'实际可访问正文',true),
 make('court','司法/执行/裁判/监管材料',[],['employment','identity'],'http',['subject','eventStage','period'],'仅可取得正文；专用查询接口待接',true),
 ...[['maimai','脉脉','maimai.cn'],['kanzhun','看准','kanzhun.com'],['zhihu','知乎','zhihu.com'],['nowcoder','牛客','nowcoder.com'],['xiaohongshu','小红书','xiaohongshu.com'],['weibo','微博','weibo.com'],['douban','豆瓣','douban.com'],['tieba','贴吧','tieba.baidu.com'],['bilibili','B站文字评论','bilibili.com'],['douyin','抖音文字评论','douyin.com']].map(([id,label,domain])=>make(id,label,[domain],['experience','opinion','recruitment'],'browser',['account','timestamp','full_text','origin'],'平台专用文字采集延期；不采视频/音频')),
 make('wechat','微信白名单群可见消息',[],['experience','opinion'],'client',['account','timestamp','context'],'本人本地客户端授权与版本兼容，适配器待接'),
 make('qq','QQ机器人事件',[],['experience','opinion'],'event',['account','timestamp','context'],'有权限的官方机器人事件，适配器待接'),
 make('group_import','用户提供群聊文本',[],['experience','opinion'],'file',['account','timestamp','context'],'用户主动导入，敏感字段仅内部使用',true),
 make('docx','DOCX 正文与表格',[],['identity','employment','finance'],'file',['full_text','table','row','column'],'python-docx 本机解析；不推断排版页码，不解析页眉页脚/批注/嵌入图片',true),
 make('xlsx','XLSX 工作表与单元格',[],['identity','employment','finance'],'file',['full_text','sheet','cell','row','column'],'openpyxl 本机只读解析；公式只保存原式，不求值或跟随外链',true),
 make('csv','CSV 字面单元格',[],['identity','employment','finance'],'file',['full_text','table','row','column'],'UTF-8/GB18030 有界本机解析；公式类文字不执行',true),
 make('ocr','PNG/JPEG/扫描 PDF 本地 OCR',[],['identity','employment','finance'],'ocr',['text','physical_page','bbox','ocr_confidence'],'RapidOCR 1.4.4 本机模型，像素/页数/时间有界；数字与主体须复核',true)
];
export function category(predicate:string,topic:string){return predicate==='identity'?'identity':predicate==='recruitment'?'recruitment':predicate==='finance'?'finance':topic==='company'?'business':topic==='position'?'employment':topic==='culture'||topic==='growth'||topic==='hours'?'experience':topic==='pay'||topic==='benefits'?'employment':'opinion';}
export function routeSources(predicate:string,topic:string,missingFields:string[]){const cat=category(predicate,topic);return sources.filter(s=>s.categories.includes(cat)).sort((a,b)=>10*(Number(b.status==='available')-Number(a.status==='available'))+Number(b.fields.some(f=>missingFields.includes(f)))-Number(a.fields.some(f=>missingFields.includes(f)))).map(s=>s.id);}
