import assert from 'node:assert/strict';
import {mkdirSync,mkdtempSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import {chromium} from '@playwright/test';
import {createServer} from '../src/server.mjs';
mkdirSync('test-results',{recursive:true});const dir=mkdtempSync(join('test-results','browser-v2-')),server=createServer({dataDir:join(dir,'data'),archiveDir:join(dir,'archive')});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const click=async id=>{await page.locator('#'+id).waitFor();await page.waitForFunction(id=>!document.getElementById(id)?.disabled,id);await page.locator('#'+id).click();};
const fillSurvey=async(anchor,pages)=>{for(let p=0;p<pages;p++){const radios=page.getByRole('radio',{name:anchor,exact:true});await radios.first().waitFor();for(let n=0;n<5;n++)await radios.nth(n).check();if(p<pages-1)await page.getByRole('button',{name:'下一页',exact:true}).click();}await click('next');};
try{
 await page.goto(origin+'/demo/a');await page.locator('#battery').selectOption('Standard');await page.locator('#mode').selectOption('demo');await click('next');
 await page.getByRole('radio',{name:'Unsure',exact:true}).first().check();await page.waitForFunction(()=>document.getElementById('notice').textContent==='已自动保存');await page.reload();assert.equal(await page.getByRole('radio',{name:'Unsure',exact:true}).first().isChecked(),true);
 await fillSurvey('Unsure',6);await page.getByRole('radio',{name:'Neither Inaccurate nor Accurate',exact:true}).first().waitFor();assert.match(await page.locator('#app').textContent(),/10\/20/);
 await fillSurvey('Neither Inaccurate nor Accurate',4);await page.locator('#value-0').selectOption('1');await page.locator('#value-2').selectOption('1');await click('next');
 await page.locator('#statement').fill('本科\n技能：了解Python\n参与项目，完成测试');await page.waitForFunction(()=>document.getElementById('notice').textContent==='已自动保存');await page.reload();assert.equal(await page.locator('#statement').inputValue(),'本科\n技能：了解Python\n参与项目，完成测试');await click('extract-statement');await page.locator('#claim-2').waitFor();assert.match(await page.locator('#claims').textContent(),/参与项目/);
 for(let i=0;i<3;i++){await page.locator(`[data-claim="${i}"][data-status="confirmed"]`).click();await page.waitForFunction(async index=>{const x=await(await fetch('/api/a/v2/bootstrap')).json();return x.sessions.at(-1).claims[index].status==='confirmed';},i);}
 await click('next');await page.getByText('补充销售指标、出差与用工条件（按需）',{exact:true}).click();await page.locator('#accept_sales_kpi').selectOption('false');await page.locator('#accept_sales_kpi-strength').selectOption('hard');await page.locator('#accept_sales_kpi-confirmed').check();await page.locator('#goals').fill('寻找软件开发机会');await click('next');
 await page.locator('[data-insight="0"][data-status="rejected"]').click();await page.waitForFunction(async()=>{const x=await(await fetch('/api/a/v2/bootstrap')).json();return x.sessions.at(-1).insights[0].status==='rejected';});
 await page.locator('[data-insight="1"][data-status="confirmed"]').click();await page.waitForFunction(async()=>{const x=await(await fetch('/api/a/v2/bootstrap')).json();return x.sessions.at(-1).insights[1].status==='confirmed';});
 await page.locator('#confirm').check();await click('next');await page.locator('#career-search').waitFor();assert.match(await page.locator('#app').textContent(),/目前兴趣尚未区分/);assert.equal(await page.locator('#download-v2').isDisabled(),true);
 await page.locator('#career-search').fill('软件开发');await click('search-careers');await page.locator('[name=direction][value="15-1252.00"]').check();await click('confirm-directions');
 const downloadPromise=page.waitForEvent('download');await click('download-v2');const download=await downloadPromise;const x=JSON.parse(readFileSync(await download.path(),'utf8'));
 assert.equal(x.ProfileBundleV2.assessments.length,2);assert(x.ProfileBundleV2.assessments.every(a=>a.complete));assert.equal(x.OccupationFitSnapshot.status,'undifferentiated_profile');assert.equal(x.SearchIntentV2.selectedDirections[0].onetCodes[0],'15-1252.00');assert.equal(x.SearchIntentV2.filters.find(c=>c.key==='accept_sales_kpi').value,false);assert.equal(x.ProfileBundleV2.values.groups[0].length,2);assert.equal(x.ProfileBundleV2.capabilities[2].description,'参与项目，完成测试');assert(x.Report.sections.find(s=>s.title==='已确认的解释').claims.length===1);
 const old=structuredClone(x.ProfileBundleV2);await page.reload();await page.locator('#download-v2').waitFor();assert.equal(await page.locator('#download-v2').isDisabled(),false);
 await click('edit');await click('next');await page.locator('#goals').fill('寻找软件测试机会');await click('next');await page.locator('#confirm').check();await click('next');await page.locator('#career-search').waitFor();assert.match(await page.locator('#app').textContent(),/画像版本 2/);
 const oldNow=await page.evaluate(async id=>await(await fetch('/api/a/v2/profiles/'+id+'?revision=1')).json(),old.profileId);assert.deepEqual(oldNow,old);
 await click('new');await page.locator('#battery').selectOption('None');await click('next');await click('next');await click('next');await page.getByText('补充其他条件',{exact:true}).click();await page.locator('#extra-key').fill('work_schedule');await page.locator('#extra-value').fill('不接受夜班');await page.locator('#extra-strength').selectOption('hard');await page.locator('#extra-confirmed').check();await click('next');await page.locator('#confirm').check();await click('next');await page.locator('#career-search').waitFor();await click('confirm-directions');await click('download-v1');await page.waitForFunction(()=>document.getElementById('notice').textContent.includes('硬条件'));
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/v2-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.setViewportSize({width:1280,height:900});await page.screenshot({path:'test-results/v2-desktop.png'});assert.deepEqual(errors,[]);
 console.log('PASS V2 browser: 50 real SurveyJS answers/save/reload, evidence confirmation/rejected insight, zero-variance, Chinese alias browse, V2 download, immutable revision 2, skip and blocked hard-constraint downgrade, mobile, no JS errors');
}catch(e){await page.screenshot({path:'test-results/v2-failure.png',fullPage:true});console.log('notice',await page.locator('#notice').textContent());throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
