"use client";
import {use,useEffect,useState} from "react";
import {PageHeader} from "@/packages/ui";
type Question={id:string;jobTitle:string;text:string};
export default function FeedbackPage({params}:{params:Promise<{id:string}>}){
 const {id}=use(params),[questions,setQuestions]=useState<Question[]>([]),[questionId,setQuestionId]=useState(""),[answer,setAnswer]=useState(""),[sourceUrl,setSourceUrl]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[result,setResult]=useState<{reportUrl:string;warnings:string[]}|null>(null);
 useEffect(()=>{void(async()=>{try{const r=await fetch("/api/integration/reports/"+id+"/feedback",{cache:"no-store"}),data=await r.json();if(!r.ok)throw Error(data.error?.message??"读取失败");setQuestions(data.questions);setQuestionId(data.questions[0]?.id??"");}catch(e){setError(e instanceof Error?e.message:"读取失败");}})();},[id]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setResult(null);try{const r=await fetch("/api/integration/reports/"+id+"/feedback",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({questionId,answer,sourceUrl})}),data=await r.json();if(!r.ok)throw Error(data.error?.message??"保存失败");setResult(data);}catch(e){setError(e instanceof Error?e.message:"保存失败");}finally{setBusy(false);}}
 return <main><PageHeader title="记下核验得到的回复"><p>把面试或调查中获得的信息放回对应岗位的问题下，另存新报告。</p></PageHeader><section className="panel"><p>用户提交的内容保留为待核验记录。系统不会仅凭一段回复宣称公司事实已证实或条件已满足。</p><form onSubmit={save} onChange={()=>setResult(null)}><fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}><label>对应问题<select value={questionId} onChange={e=>setQuestionId(e.target.value)} required>{questions.map(q=><option key={q.id} value={q.id}>{q.jobTitle} · {q.text}</option>)}</select></label><label>获得的回复<textarea value={answer} onChange={e=>setAnswer(e.target.value)} maxLength={6000} required rows={6}/></label><label>来源链接（选填）<input type="url" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} maxLength={2000}/></label><button disabled={busy||!questionId}>{busy?"保存中…":"保存记录并生成新报告"}</button></fieldset></form></section>{error&&<p role="alert">{error}</p>}{result&&<section className="panel"><h2>核验记录已保存</h2>{result.warnings.map(w=><p key={w}>{w}</p>)}<a href={result.reportUrl}>查看包含回复的新报告 →</a></section>}<p><a href={"/flow/reports/"+id}>回到原报告</a> · <a href="/history">我的报告</a></p></main>;
}
