import {escapeHtml as e} from '../c-report/ui/render-html';
import type {V3Snapshot} from './v3-contract';
const labels:Record<string,string>={applicable:'范围对应',conditional:'有条件或范围不全',unconfirmed:'未确认',unrelated:'主体不符',source_statement:'来源如何表述',applicable_arrangement:'该岗位适用安排',observed_practice:'实际执行情况',min:'下限',max:'上限',currency:'币种',period:'时期或计薪周期',basis:'固定/浮动口径',taxBasis:'税前税后',effectiveConditions:'生效条件',role:'岗位',mechanism:'具体机制',eligibility:'参加条件',frequency:'频率',mandatory:'是否强制',value:'数值',unit:'单位',reportingScope:'报表范围',applicable_source_answer:'已有适用范围的来源回答',source_attempts_complete:'问题补查已结束',task_budget_exhausted:'达到任务预算',no_effective_new_material:'补查未取得有效新材料',reused_frozen_sources:'重新判断已保存材料，未联网',request_outcome_unknown:'请求结果不明，保留预算且不自动重试',user_meaning_not_confirmed:'需先明确个人偏好的含义',exact:'法人名称对应',alias:'仅简称线索',company:'公司层面',job:'该岗位',team:'团队',business:'业务',ok:'取得材料',empty:'无搜索结果',blocked:'访问受限',rate_limited:'访问限流',timeout:'访问超时',parse_error:'解析失败',identity_mismatch:'主体不符',budget_exhausted:'达到请求预算',full_text:'正文',document:'文本 PDF',index_snippet:'搜索摘要',partial_text:'摘录',navigation_only:'导航页',unusable:'不可用于判断',accepted:'可作来源陈述',quarantined:'待核范围',rejected:'未进入判断'};
const label=(v:string)=>labels[v]??v;
export function renderV3Report(s:V3Snapshot|undefined,reportId:string){
 if(!s)return '';
 const state={answered:'已回答（来源陈述）',partial:'部分回答',conflicting:'可比陈述存在冲突',unknown:'未知',not_applicable:'明确不适用'};
 const citation=(id:string)=>{const c=s.claims.find(c=>c.id===id);if(!c)return '';const loc=Object.entries(c.locator).map(([k,v])=>(k==='physical_page'?'PDF 第':k==='paragraph'?'段落 ':k==='table'?'表 ':k==='row'?'行 ':'列 ')+v).join('，');return '<blockquote>'+e(c.quote)+'</blockquote><p>来源声称，尚待核验；'+e(label(c.scope))+'；'+e(label(c.subjectMatch))+'；时期：'+e(c.period??'未明示')+'；条件：'+e(c.conditions.join('、')||'未明示')+'；位置：'+e(loc)+' <a href="/api/integration/reports/'+e(reportId)+'/sources/'+e(c.evidenceId)+'">回读已保存原文</a></p>';};
 return '<section class="card" id="v3-questions"><h2>具体问题与需求判断</h2>'+(s.needOrigin==='synthetic_acceptance'?'<p><strong>合成验收需求：仅用于验证流程，不代表你的求职侧写。材料来源另行标注。</strong></p>':'')+(s.materialKind!=='real_sources'?'<p><strong>本报告包含合成规则测试材料，不可据此判断真实企业待遇。</strong></p>':'')+'<p>取得材料、回答问题、证实陈述和满足需求分别处理。来源陈述尚未独立认证。</p><p>'+e(s.model.reason)+'</p>'+
 '<p>关键未知 '+s.criticalUnknownCount+' 项；内部待复核 '+s.reviews.filter(r=>r.state==='deferred'||r.state==='pending').length+' 项。'+(s.criticalUnknownCount>3?'现有材料无法筛出明确满足全部关键要求的候选。':'')+'</p>'+
 s.questions.map(q=>'<details '+(q.importance==='hard'?'open':'')+'><summary>'+e(q.text)+' · '+e(state[q.answerState])+'</summary><p>适用性：'+e(label(q.applicability))+'；需求满足：'+e(q.conclusion==='pass'?'满足':q.conclusion==='fail'?'不满足':'未知')+'；回答目标：'+e(label(q.answerTarget))+'</p><p>缺失：'+e(q.missingFields.map(label).join('、')||'无')+'；补查 '+q.attempts+'/'+q.maxAttempts+'；停止原因：'+e(label(q.stopReason??'未停止'))+'</p>'+q.supportingClaimIds.slice(0,3).map(citation).join('')+(q.supportingClaimIds.length>3?'<details><summary>其余 '+(q.supportingClaimIds.length-3)+' 条来源陈述</summary>'+q.supportingClaimIds.slice(3).map(citation).join('')+'</details>':'')+(q.nextAction==='preference_clarification'?'<p>在个人需求页选择具体关注项目后，再作定向调查。</p>':'')+'</details>').join('')+
 '<p>关键外部问题见上方综合结论；其余未知保留在具体问题中。</p><details><summary>语义复查、来源能力与预算记录</summary><p>已知网络请求 '+s.budget.usedRequests+'，结果不明预留 '+s.budget.reservedRequests+'，总上限 '+s.budget.maxRequests+'；累计执行耗时 '+Math.round(s.budget.elapsedMs/1000)+' 秒；模型调用 '+s.budget.modelCalls+'；总费用 '+(s.budget.costMinor===null?'未知':s.budget.costMinor)+'</p><p>'+e(s.propagation.reason)+'</p>'+s.semanticChecks.map(c=>'<p>语义复查线索（不作独立证据）：'+e(c.quote)+'；'+e(c.reason)+'；缺失 '+e(c.missingFields.map(label).join('、')||'未提出')+'</p>').join('')+
 s.sourceAttempts.map(a=>'<p>'+e(a.acquisitionMode==='local_database'?'本地候选库':a.acquisitionMode.startsWith('user_')?'用户提供，未经核验':a.acquisitionMode==='search'?'有界搜索':'公开资料')+' · '+e(label(a.accessState))+' / '+e(label(a.contentState))+' / '+e(label(a.analysisState))+'；'+e(a.declaredSource?'提供者声明来源：'+a.declaredSource+'（未认证）':a.failureReason??'已保存')+'；发布 '+e(a.publishedAt??'未知')+'；获取 '+e(a.retrievedAt)+'</p>').join('')+'</details></section>';
}
